*** Starting uWSGI 2.0.11.1 (64bit) on [Thu Jun 16 15:20:59 2016] ***
compiled with version: 4.8.3 20140911 (Red Hat 4.8.3-9) on 20 August 2015 15:10:12
os: Linux-3.10.0-327.4.4.el7.x86_64 #1 SMP Thu Dec 17 15:51:24 EST 2015
nodename: hz-10-160-156-96.internal.lede.com
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 4
current working directory: /home/dlgao/project
writing pidfile to /home/dlgao/project/logs/uwsgi.pid
detected binary path: /usr/bin/uwsgi
chdir() to /home/dlgao/project
your processes number limit is 4096
your memory page size is 4096 bytes
detected max file descriptor number: 131072
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 127.0.0.1:9102 fd 3
Python version: 2.7.5 (default, Oct 11 2015, 17:47:16)  [GCC 4.8.3 20140911 (Red Hat 4.8.3-9)]
Python main interpreter initialized at 0x123ec70
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 218304 bytes (213 KB) for 2 cores
*** Operational MODE: preforking ***
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x123ec70 pid: 22032 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 22032)
spawned uWSGI worker 1 (pid: 22033, cores: 1)
spawned uWSGI worker 2 (pid: 22034, cores: 1)
Thu Jun 16 15:24:58 2016 - *** /home/dlgao/project/uwsgi.ini has been touched... grace them all !!! ***
...gracefully killing workers...
Gracefully killing worker 2 (pid: 22034)...
Gracefully killing worker 1 (pid: 22033)...
worker 1 buried after 1 seconds
worker 2 buried after 1 seconds
binary reloading uWSGI...
chdir() to /home/dlgao/project
closing all non-uwsgi socket fds > 2 (max_fd = 131072)...
found fd 3 mapped to socket 0 (127.0.0.1:9102)
running /usr/bin/uwsgi
[uWSGI] getting INI configuration from uwsgi.ini
open("./python_plugin.so"): No such file or directory [core/utils.c line 3675]
!!! UNABLE to load uWSGI plugin: ./python_plugin.so: cannot open shared object file: No such file or directory !!!
*** Starting uWSGI 2.0.11.1 (64bit) on [Thu Jun 16 15:24:59 2016] ***
compiled with version: 4.8.3 20140911 (Red Hat 4.8.3-9) on 20 August 2015 15:10:12
os: Linux-3.10.0-327.4.4.el7.x86_64 #1 SMP Thu Dec 17 15:51:24 EST 2015
nodename: hz-10-160-156-96.internal.lede.com
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 4
current working directory: /home/dlgao/project
detected binary path: /usr/bin/uwsgi
chdir() to /home/dlgao/project
your processes number limit is 4096
your memory page size is 4096 bytes
detected max file descriptor number: 131072
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 10.160.156.96:9102 fd 3
Python version: 2.7.5 (default, Oct 11 2015, 17:47:16)  [GCC 4.8.3 20140911 (Red Hat 4.8.3-9)]
Python main interpreter initialized at 0x2184b40
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 218304 bytes (213 KB) for 2 cores
*** Operational MODE: preforking ***
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x2184b40 pid: 22032 (default app)
*** uWSGI is running in multiple interpreter mode ***
gracefully (RE)spawned uWSGI master process (pid: 22032)
spawned uWSGI worker 1 (pid: 22072, cores: 1)
spawned uWSGI worker 2 (pid: 22073, cores: 1)
Thu Jun 16 15:25:02 2016 - *** /home/dlgao/project/uwsgi.ini has been touched... grace them all !!! ***
...gracefully killing workers...
Gracefully killing worker 2 (pid: 22073)...
Gracefully killing worker 1 (pid: 22072)...
worker 1 buried after 1 seconds
worker 2 buried after 1 seconds
binary reloading uWSGI...
chdir() to /home/dlgao/project
closing all non-uwsgi socket fds > 2 (max_fd = 131072)...
found fd 3 mapped to socket 0 (10.160.156.96:9102)
running /usr/bin/uwsgi
[uWSGI] getting INI configuration from uwsgi.ini
open("./python_plugin.so"): No such file or directory [core/utils.c line 3675]
!!! UNABLE to load uWSGI plugin: ./python_plugin.so: cannot open shared object file: No such file or directory !!!
*** Starting uWSGI 2.0.11.1 (64bit) on [Thu Jun 16 15:25:03 2016] ***
compiled with version: 4.8.3 20140911 (Red Hat 4.8.3-9) on 20 August 2015 15:10:12
os: Linux-3.10.0-327.4.4.el7.x86_64 #1 SMP Thu Dec 17 15:51:24 EST 2015
nodename: hz-10-160-156-96.internal.lede.com
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 4
current working directory: /home/dlgao/project
detected binary path: /usr/bin/uwsgi
chdir() to /home/dlgao/project
your processes number limit is 4096
your memory page size is 4096 bytes
detected max file descriptor number: 131072
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 inherited INET address 10.160.156.96:9102 fd 3
Python version: 2.7.5 (default, Oct 11 2015, 17:47:16)  [GCC 4.8.3 20140911 (Red Hat 4.8.3-9)]
Python main interpreter initialized at 0x1b62780
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 218304 bytes (213 KB) for 2 cores
*** Operational MODE: preforking ***
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x1b62780 pid: 22032 (default app)
*** uWSGI is running in multiple interpreter mode ***
gracefully (RE)spawned uWSGI master process (pid: 22032)
spawned uWSGI worker 1 (pid: 22085, cores: 1)
spawned uWSGI worker 2 (pid: 22086, cores: 1)
Thu Jun 16 15:25:12 2016 - *** /home/dlgao/project/uwsgi.ini has been touched... grace them all !!! ***
...gracefully killing workers...
Gracefully killing worker 1 (pid: 22085)...
Gracefully killing worker 2 (pid: 22086)...
worker 1 buried after 1 seconds
worker 2 buried after 1 seconds
binary reloading uWSGI...
chdir() to /home/dlgao/project
closing all non-uwsgi socket fds > 2 (max_fd = 131072)...
found fd 3 mapped to socket 0 (10.160.156.96:9102)
running /usr/bin/uwsgi
[uWSGI] getting INI configuration from uwsgi.ini
open("./python_plugin.so"): No such file or directory [core/utils.c line 3675]
!!! UNABLE to load uWSGI plugin: ./python_plugin.so: cannot open shared object file: No such file or directory !!!
*** Starting uWSGI 2.0.11.1 (64bit) on [Thu Jun 16 15:25:13 2016] ***
compiled with version: 4.8.3 20140911 (Red Hat 4.8.3-9) on 20 August 2015 15:10:12
os: Linux-3.10.0-327.4.4.el7.x86_64 #1 SMP Thu Dec 17 15:51:24 EST 2015
nodename: hz-10-160-156-96.internal.lede.com
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 4
current working directory: /home/dlgao/project
detected binary path: /usr/bin/uwsgi
chdir() to /home/dlgao/project
your processes number limit is 4096
your memory page size is 4096 bytes
detected max file descriptor number: 131072
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 inherited INET address 10.160.156.96:9102 fd 3
Python version: 2.7.5 (default, Oct 11 2015, 17:47:16)  [GCC 4.8.3 20140911 (Red Hat 4.8.3-9)]
Python main interpreter initialized at 0x1a86780
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 218304 bytes (213 KB) for 2 cores
*** Operational MODE: preforking ***
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x1a86780 pid: 22032 (default app)
*** uWSGI is running in multiple interpreter mode ***
gracefully (RE)spawned uWSGI master process (pid: 22032)
spawned uWSGI worker 1 (pid: 22091, cores: 1)
spawned uWSGI worker 2 (pid: 22092, cores: 1)
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/web.py-0.37-py2.7.egg/web/application.py", line 239, in process
    return self.handle()
  File "/usr/lib/python2.7/site-packages/web.py-0.37-py2.7.egg/web/application.py", line 230, in handle
    return self._delegate(fn, self.fvars, args)
  File "/usr/lib/python2.7/site-packages/web.py-0.37-py2.7.egg/web/application.py", line 416, in _delegate
    mod = __import__(mod, None, None, [''])
  File "./app/controllers/nginxmonitor.py", line 13, in <module>
    from app.helpers import bus
  File "./app/helpers/bus.py", line 8, in <module>
    import xmltodict
ImportError: No module named xmltodict

[pid: 22092|app: 0|req: 1/1] 101.226.103.72 () {38 vars in 709 bytes} [Thu Jun 16 15:25:20 2016] GET /functiontest?signature=c8d3d30085824c05c53cac0d5a7be0f996b1a8fc&echostr=9079606066126149221&timestamp=1466061920&nonce=716490191 => generated 51996 bytes in 83 msecs (HTTP/1.0 500) 1 headers in 63 bytes (2 switches on core 0)
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/web.py-0.37-py2.7.egg/web/application.py", line 239, in process
    return self.handle()
  File "/usr/lib/python2.7/site-packages/web.py-0.37-py2.7.egg/web/application.py", line 230, in handle
    return self._delegate(fn, self.fvars, args)
  File "/usr/lib/python2.7/site-packages/web.py-0.37-py2.7.egg/web/application.py", line 416, in _delegate
    mod = __import__(mod, None, None, [''])
  File "./app/controllers/nginxmonitor.py", line 13, in <module>
    from app.helpers import bus
  File "./app/helpers/bus.py", line 8, in <module>
    import xmltodict
ImportError: No module named xmltodict

[pid: 22092|app: 0|req: 2/2] 58.247.206.143 () {38 vars in 709 bytes} [Thu Jun 16 15:27:17 2016] GET /functiontest?signature=f4197ef4ef98d918145595ab5d57d360b3659719&echostr=8857707031740774399&timestamp=1466062037&nonce=381663636 => generated 51996 bytes in 13 msecs (HTTP/1.0 500) 1 headers in 63 bytes (2 switches on core 0)
*** Starting uWSGI 2.0.11.1 (64bit) on [Thu Jun 16 15:28:06 2016] ***
compiled with version: 4.8.3 20140911 (Red Hat 4.8.3-9) on 20 August 2015 15:10:12
os: Linux-3.10.0-327.4.4.el7.x86_64 #1 SMP Thu Dec 17 15:51:24 EST 2015
nodename: hz-10-160-156-96.internal.lede.com
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 4
current working directory: /home/dlgao/project
writing pidfile to /home/dlgao/project/logs/uwsgi.pid
detected binary path: /usr/bin/uwsgi
chdir() to /home/dlgao/project
your processes number limit is 4096
your memory page size is 4096 bytes
detected max file descriptor number: 131072
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 10.160.156.96:9102 fd 3
Python version: 2.7.5 (default, Oct 11 2015, 17:47:16)  [GCC 4.8.3 20140911 (Red Hat 4.8.3-9)]
Python main interpreter initialized at 0x2703c70
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 218304 bytes (213 KB) for 2 cores
*** Operational MODE: preforking ***
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x2703c70 pid: 22160 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 22160)
spawned uWSGI worker 1 (pid: 22161, cores: 1)
spawned uWSGI worker 2 (pid: 22162, cores: 1)
[pid: 22161|app: 0|req: 1/1] 140.207.54.80 () {38 vars in 710 bytes} [Thu Jun 16 15:28:12 2016] GET /functiontest?signature=41db4d142cd85ca4dc139af5b1ad966e3fee30f1&echostr=8941446622620637119&timestamp=1466062092&nonce=1273701182 => generated 19 bytes in 52 msecs (HTTP/1.0 200) 0 headers in 19 bytes (2 switches on core 0)
['909'] 909
device_id=f8:a4:5f:11:21:79is_exact=0keywords=909timestamp=2016-03-31 15:39:00client_credentialsf8:a4:5f:11:21:79
OrderedDict([('device_id', 'f8:a4:5f:11:21:79'), ('is_exact', 0), ('keywords', '909'), ('timestamp', '2016-03-31 15:39:00')]) 5ec2820150a9014c4334988bc534191f
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/web.py-0.37-py2.7.egg/web/application.py", line 239, in process
    return self.handle()
  File "/usr/lib/python2.7/site-packages/web.py-0.37-py2.7.egg/web/application.py", line 230, in handle
    return self._delegate(fn, self.fvars, args)
  File "/usr/lib/python2.7/site-packages/web.py-0.37-py2.7.egg/web/application.py", line 420, in _delegate
    return handle_class(cls)
  File "/usr/lib/python2.7/site-packages/web.py-0.37-py2.7.egg/web/application.py", line 396, in handle_class
    return tocall(*args)
  File "./app/controllers/nginxmonitor.py", line 66, in POST
    busId  = bus.requestRouteId(keyWord)
  File "./app/helpers/bus.py", line 77, in requestRouteId
    resHtml = open(fileGz,"w")
IOError: [Errno 13] Permission denied: 'tmpfile17059ad0-3394-11e6-a03b-525400faad6c.gz'

[pid: 22161|app: 0|req: 2/2] 140.207.54.77 () {42 vars in 933 bytes} [Thu Jun 16 15:29:41 2016] POST /functiontest?signature=9bb9dab814eb1b2b99a93a4752d47bd96788d316&timestamp=1466062181&nonce=1825445448&openid=oNqycwWK96VhQHx5eM0rBzaUrfZ4&encrypt_type=aes&msg_signature=21ca1dd6a2177abf35eefea1bd1597a0d3c94bd0 => generated 39674 bytes in 444 msecs (HTTP/1.1 500) 1 headers in 63 bytes (2 switches on core 0)
['909'] 909
device_id=f8:a4:5f:11:21:79is_exact=0keywords=909timestamp=2016-03-31 15:39:00client_credentialsf8:a4:5f:11:21:79
OrderedDict([('device_id', 'f8:a4:5f:11:21:79'), ('is_exact', 0), ('keywords', '909'), ('timestamp', '2016-03-31 15:39:00')]) 5ec2820150a9014c4334988bc534191f
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/web.py-0.37-py2.7.egg/web/application.py", line 239, in process
    return self.handle()
  File "/usr/lib/python2.7/site-packages/web.py-0.37-py2.7.egg/web/application.py", line 230, in handle
    return self._delegate(fn, self.fvars, args)
  File "/usr/lib/python2.7/site-packages/web.py-0.37-py2.7.egg/web/application.py", line 420, in _delegate
    return handle_class(cls)
  File "/usr/lib/python2.7/site-packages/web.py-0.37-py2.7.egg/web/application.py", line 396, in handle_class
    return tocall(*args)
  File "./app/controllers/nginxmonitor.py", line 66, in POST
    busId  = bus.requestRouteId(keyWord)
  File "./app/helpers/bus.py", line 77, in requestRouteId
    resHtml = open(fileGz,"w")
IOError: [Errno 13] Permission denied: 'tmpfile1d28a65a-3394-11e6-a03b-525400faad6c.gz'

[pid: 22161|app: 0|req: 3/3] 140.207.54.77 () {42 vars in 933 bytes} [Thu Jun 16 15:29:51 2016] POST /functiontest?signature=1e41c2d4529bf7a4f37e5f799d3ea936ccd2f44b&timestamp=1466062191&nonce=1132284410&openid=oNqycwWK96VhQHx5eM0rBzaUrfZ4&encrypt_type=aes&msg_signature=1d89da658215f782b929257ba55464aa20948ffb => generated 39674 bytes in 129 msecs (HTTP/1.1 500) 1 headers in 63 bytes (2 switches on core 0)
['909'] 909
device_id=f8:a4:5f:11:21:79is_exact=0keywords=909timestamp=2016-03-31 15:39:00client_credentialsf8:a4:5f:11:21:79
OrderedDict([('device_id', 'f8:a4:5f:11:21:79'), ('is_exact', 0), ('keywords', '909'), ('timestamp', '2016-03-31 15:39:00')]) 5ec2820150a9014c4334988bc534191f
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/web.py-0.37-py2.7.egg/web/application.py", line 239, in process
    return self.handle()
  File "/usr/lib/python2.7/site-packages/web.py-0.37-py2.7.egg/web/application.py", line 230, in handle
    return self._delegate(fn, self.fvars, args)
  File "/usr/lib/python2.7/site-packages/web.py-0.37-py2.7.egg/web/application.py", line 420, in _delegate
    return handle_class(cls)
  File "/usr/lib/python2.7/site-packages/web.py-0.37-py2.7.egg/web/application.py", line 396, in handle_class
    return tocall(*args)
  File "./app/controllers/nginxmonitor.py", line 66, in POST
    busId  = bus.requestRouteId(keyWord)
  File "./app/helpers/bus.py", line 77, in requestRouteId
    resHtml = open(fileGz,"w")
IOError: [Errno 13] Permission denied: 'tmpfile23eaa1c8-3394-11e6-86df-525400faad6c.gz'

[pid: 22162|app: 0|req: 1/4] 140.207.54.77 () {42 vars in 931 bytes} [Thu Jun 16 15:30:02 2016] POST /functiontest?signature=901dba150d1fb5db2fcce29e71f0c6df6dd05a45&timestamp=1466062201&nonce=962502042&openid=oNqycwWK96VhQHx5eM0rBzaUrfZ4&encrypt_type=aes&msg_signature=9909accbbece7241f980ff1d59dd7672dfeb7df1 => generated 39669 bytes in 1261 msecs (HTTP/1.1 500) 1 headers in 63 bytes (2 switches on core 0)
Thu Jun 16 15:30:46 2016 - *** /home/dlgao/project/uwsgi.ini has been touched... grace them all !!! ***
...gracefully killing workers...
Gracefully killing worker 1 (pid: 22161)...
Gracefully killing worker 2 (pid: 22162)...
worker 1 buried after 1 seconds
worker 2 buried after 1 seconds
binary reloading uWSGI...
chdir() to /home/dlgao/project
closing all non-uwsgi socket fds > 2 (max_fd = 131072)...
found fd 3 mapped to socket 0 (10.160.156.96:9102)
running /usr/bin/uwsgi
[uWSGI] getting INI configuration from uwsgi.ini
open("./python_plugin.so"): No such file or directory [core/utils.c line 3675]
!!! UNABLE to load uWSGI plugin: ./python_plugin.so: cannot open shared object file: No such file or directory !!!
*** Starting uWSGI 2.0.11.1 (64bit) on [Thu Jun 16 15:30:47 2016] ***
compiled with version: 4.8.3 20140911 (Red Hat 4.8.3-9) on 20 August 2015 15:10:12
os: Linux-3.10.0-327.4.4.el7.x86_64 #1 SMP Thu Dec 17 15:51:24 EST 2015
nodename: hz-10-160-156-96.internal.lede.com
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 4
current working directory: /home/dlgao/project
detected binary path: /usr/bin/uwsgi
chdir() to /home/dlgao/project
your processes number limit is 4096
your memory page size is 4096 bytes
detected max file descriptor number: 131072
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 inherited INET address 10.160.156.96:9102 fd 3
Python version: 2.7.5 (default, Oct 11 2015, 17:47:16)  [GCC 4.8.3 20140911 (Red Hat 4.8.3-9)]
Python main interpreter initialized at 0x1887780
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 218304 bytes (213 KB) for 2 cores
*** Operational MODE: preforking ***
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x1887780 pid: 22160 (default app)
*** uWSGI is running in multiple interpreter mode ***
gracefully (RE)spawned uWSGI master process (pid: 22160)
spawned uWSGI worker 1 (pid: 22244, cores: 1)
spawned uWSGI worker 2 (pid: 22245, cores: 1)
Thu Jun 16 15:30:50 2016 - *** /home/dlgao/project/uwsgi.ini has been touched... grace them all !!! ***
...gracefully killing workers...
Gracefully killing worker 2 (pid: 22245)...
Gracefully killing worker 1 (pid: 22244)...
worker 1 buried after 1 seconds
worker 2 buried after 1 seconds
binary reloading uWSGI...
chdir() to /home/dlgao/project
closing all non-uwsgi socket fds > 2 (max_fd = 131072)...
found fd 3 mapped to socket 0 (10.160.156.96:9102)
running /usr/bin/uwsgi
[uWSGI] getting INI configuration from uwsgi.ini
open("./python_plugin.so"): No such file or directory [core/utils.c line 3675]
!!! UNABLE to load uWSGI plugin: ./python_plugin.so: cannot open shared object file: No such file or directory !!!
*** Starting uWSGI 2.0.11.1 (64bit) on [Thu Jun 16 15:30:51 2016] ***
compiled with version: 4.8.3 20140911 (Red Hat 4.8.3-9) on 20 August 2015 15:10:12
os: Linux-3.10.0-327.4.4.el7.x86_64 #1 SMP Thu Dec 17 15:51:24 EST 2015
nodename: hz-10-160-156-96.internal.lede.com
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 4
current working directory: /home/dlgao/project
detected binary path: /usr/bin/uwsgi
chdir() to /home/dlgao/project
your processes number limit is 4096
your memory page size is 4096 bytes
detected max file descriptor number: 131072
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 inherited INET address 10.160.156.96:9102 fd 3
Python version: 2.7.5 (default, Oct 11 2015, 17:47:16)  [GCC 4.8.3 20140911 (Red Hat 4.8.3-9)]
Python main interpreter initialized at 0x849780
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 218304 bytes (213 KB) for 2 cores
*** Operational MODE: preforking ***
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x849780 pid: 22160 (default app)
*** uWSGI is running in multiple interpreter mode ***
gracefully (RE)spawned uWSGI master process (pid: 22160)
spawned uWSGI worker 1 (pid: 22248, cores: 1)
spawned uWSGI worker 2 (pid: 22249, cores: 1)
['909'] 909
device_id=f8:a4:5f:11:21:79is_exact=0keywords=909timestamp=2016-03-31 15:39:00client_credentialsf8:a4:5f:11:21:79
OrderedDict([('device_id', 'f8:a4:5f:11:21:79'), ('is_exact', 0), ('keywords', '909'), ('timestamp', '2016-03-31 15:39:00')]) 5ec2820150a9014c4334988bc534191f
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/web.py-0.37-py2.7.egg/web/application.py", line 239, in process
    return self.handle()
  File "/usr/lib/python2.7/site-packages/web.py-0.37-py2.7.egg/web/application.py", line 230, in handle
    return self._delegate(fn, self.fvars, args)
  File "/usr/lib/python2.7/site-packages/web.py-0.37-py2.7.egg/web/application.py", line 420, in _delegate
    return handle_class(cls)
  File "/usr/lib/python2.7/site-packages/web.py-0.37-py2.7.egg/web/application.py", line 396, in handle_class
    return tocall(*args)
  File "./app/controllers/nginxmonitor.py", line 66, in POST
    busId  = bus.requestRouteId(keyWord)
  File "./app/helpers/bus.py", line 77, in requestRouteId
    resHtml = open(fileGz,"w")
IOError: [Errno 13] Permission denied: 'tmpfile46cc5c36-3394-11e6-bf6b-525400faad6c.gz'

[pid: 22249|app: 0|req: 1/1] 140.207.54.77 () {42 vars in 933 bytes} [Thu Jun 16 15:31:00 2016] POST /functiontest?signature=79cf00ca3f22d833e67d61513d2b98374e71dd14&timestamp=1466062260&nonce=2022597570&openid=oNqycwWK96VhQHx5eM0rBzaUrfZ4&encrypt_type=aes&msg_signature=df6f1a792547e6c581103ec4e49834d83a57177b => generated 39657 bytes in 983 msecs (HTTP/1.1 500) 1 headers in 63 bytes (2 switches on core 0)
['909'] 909
device_id=f8:a4:5f:11:21:79is_exact=0keywords=909timestamp=2016-03-31 15:39:00client_credentialsf8:a4:5f:11:21:79
OrderedDict([('device_id', 'f8:a4:5f:11:21:79'), ('is_exact', 0), ('keywords', '909'), ('timestamp', '2016-03-31 15:39:00')]) 5ec2820150a9014c4334988bc534191f
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/web.py-0.37-py2.7.egg/web/application.py", line 239, in process
    return self.handle()
  File "/usr/lib/python2.7/site-packages/web.py-0.37-py2.7.egg/web/application.py", line 230, in handle
    return self._delegate(fn, self.fvars, args)
  File "/usr/lib/python2.7/site-packages/web.py-0.37-py2.7.egg/web/application.py", line 420, in _delegate
    return handle_class(cls)
  File "/usr/lib/python2.7/site-packages/web.py-0.37-py2.7.egg/web/application.py", line 396, in handle_class
    return tocall(*args)
  File "./app/controllers/nginxmonitor.py", line 66, in POST
    busId  = bus.requestRouteId(keyWord)
  File "./app/helpers/bus.py", line 77, in requestRouteId
    resHtml = open(fileGz,"w")
IOError: [Errno 13] Permission denied: 'tmpfile4ced5eda-3394-11e6-bf6b-525400faad6c.gz'

[pid: 22249|app: 0|req: 2/2] 140.207.54.77 () {42 vars in 931 bytes} [Thu Jun 16 15:31:11 2016] POST /functiontest?signature=e66f35a369d5a536bb6245bcaf8cd61f6645d6d6&timestamp=1466062271&nonce=959431094&openid=oNqycwWK96VhQHx5eM0rBzaUrfZ4&encrypt_type=aes&msg_signature=951ed62839f6ffcbcc8c5fb9aade6a537fa1a72d => generated 39652 bytes in 136 msecs (HTTP/1.1 500) 1 headers in 63 bytes (2 switches on core 0)
['909'] 909
device_id=f8:a4:5f:11:21:79is_exact=0keywords=909timestamp=2016-03-31 15:39:00client_credentialsf8:a4:5f:11:21:79
OrderedDict([('device_id', 'f8:a4:5f:11:21:79'), ('is_exact', 0), ('keywords', '909'), ('timestamp', '2016-03-31 15:39:00')]) 5ec2820150a9014c4334988bc534191f
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/web.py-0.37-py2.7.egg/web/application.py", line 239, in process
    return self.handle()
  File "/usr/lib/python2.7/site-packages/web.py-0.37-py2.7.egg/web/application.py", line 230, in handle
    return self._delegate(fn, self.fvars, args)
  File "/usr/lib/python2.7/site-packages/web.py-0.37-py2.7.egg/web/application.py", line 420, in _delegate
    return handle_class(cls)
  File "/usr/lib/python2.7/site-packages/web.py-0.37-py2.7.egg/web/application.py", line 396, in handle_class
    return tocall(*args)
  File "./app/controllers/nginxmonitor.py", line 66, in POST
    busId  = bus.requestRouteId(keyWord)
  File "./app/helpers/bus.py", line 77, in requestRouteId
    resHtml = open(fileGz,"w")
IOError: [Errno 13] Permission denied: 'tmpfile53102f9a-3394-11e6-ba8c-525400faad6c.gz'

[pid: 22248|app: 0|req: 1/3] 140.207.54.77 () {42 vars in 931 bytes} [Thu Jun 16 15:31:22 2016] POST /functiontest?signature=0ae86a462774be10789b1e614bda179bb4a027eb&timestamp=1466062282&nonce=748655274&openid=oNqycwWK96VhQHx5eM0rBzaUrfZ4&encrypt_type=aes&msg_signature=a5d2ac725f4b66f33ba7012564dd96feb3d2c5ce => generated 39652 bytes in 234 msecs (HTTP/1.1 500) 1 headers in 63 bytes (2 switches on core 0)
*** Starting uWSGI 2.0.11.1 (64bit) on [Thu Jun 16 15:33:55 2016] ***
compiled with version: 4.8.3 20140911 (Red Hat 4.8.3-9) on 20 August 2015 15:10:12
os: Linux-3.10.0-327.4.4.el7.x86_64 #1 SMP Thu Dec 17 15:51:24 EST 2015
nodename: hz-10-160-156-96.internal.lede.com
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 4
current working directory: /home/dlgao/project
writing pidfile to /home/dlgao/project/logs/uwsgi.pid
detected binary path: /usr/bin/uwsgi
chdir() to /home/dlgao/project
your processes number limit is 4096
your memory page size is 4096 bytes
detected max file descriptor number: 131072
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 10.160.156.96:9102 fd 3
Python version: 2.7.5 (default, Oct 11 2015, 17:47:16)  [GCC 4.8.3 20140911 (Red Hat 4.8.3-9)]
Python main interpreter initialized at 0x21f0c60
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 218304 bytes (213 KB) for 2 cores
*** Operational MODE: preforking ***
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x21f0c60 pid: 22288 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 22288)
spawned uWSGI worker 1 (pid: 22289, cores: 1)
spawned uWSGI worker 2 (pid: 22290, cores: 1)
*** Starting uWSGI 2.0.11.1 (64bit) on [Thu Jun 16 15:34:26 2016] ***
compiled with version: 4.8.3 20140911 (Red Hat 4.8.3-9) on 20 August 2015 15:10:12
os: Linux-3.10.0-327.4.4.el7.x86_64 #1 SMP Thu Dec 17 15:51:24 EST 2015
nodename: hz-10-160-156-96.internal.lede.com
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 4
current working directory: /home/dlgao/project
writing pidfile to /home/dlgao/project/logs/uwsgi.pid
detected binary path: /usr/bin/uwsgi
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /home/dlgao/project
your processes number limit is 31147
your memory page size is 4096 bytes
detected max file descriptor number: 131072
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 10.160.156.96:9102 fd 3
Python version: 2.7.5 (default, Oct 11 2015, 17:47:16)  [GCC 4.8.3 20140911 (Red Hat 4.8.3-9)]
Python main interpreter initialized at 0x1ed24f0
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 218304 bytes (213 KB) for 2 cores
*** Operational MODE: preforking ***
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x1ed24f0 pid: 22317 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 22317)
spawned uWSGI worker 1 (pid: 22318, cores: 1)
spawned uWSGI worker 2 (pid: 22319, cores: 1)
['909'] 909
device_id=f8:a4:5f:11:21:79is_exact=0keywords=909timestamp=2016-03-31 15:39:00client_credentialsf8:a4:5f:11:21:79
OrderedDict([('device_id', 'f8:a4:5f:11:21:79'), ('is_exact', 0), ('keywords', '909'), ('timestamp', '2016-03-31 15:39:00')]) 5ec2820150a9014c4334988bc534191f
device_id=f8:a4:5f:11:21:79index=1is_change=0route_id=1753timestamp=2016-03-31 15:39:02type=0client_credentialsf8:a4:5f:11:21:79
device_id=f8:a4:5f:11:21:79index=1is_change=1route_id=1753timestamp=2016-03-31 15:39:02type=0client_credentialsf8:a4:5f:11:21:79
$$$$$$$$$$$$$$$$$bus$$$$$$$$$$$$$$$$ {u'1753': u'\u957f\u5efa\u9a7e\u6821 \u81f3 \u571f\u4e95\u6751\u897f\u53e3', u'2049': u'\u571f\u4e95\u6751\u897f\u53e3 \u81f3 \u957f\u5efa\u9a7e\u6821'}
################nginxmonitor################## {"1753": "\u957f\u5efa\u9a7e\u6821 \u81f3 \u571f\u4e95\u6751\u897f\u53e3", "2049": "\u571f\u4e95\u6751\u897f\u53e3 \u81f3 \u957f\u5efa\u9a7e\u6821"}
[pid: 22319|app: 0|req: 1/1] 140.207.54.77 () {42 vars in 931 bytes} [Thu Jun 16 15:34:43 2016] POST /functiontest?signature=85b6f66fbc3007dd9980b83bd3100e351c876d24&timestamp=1466062483&nonce=585286336&openid=oNqycwWK96VhQHx5eM0rBzaUrfZ4&encrypt_type=aes&msg_signature=c49ff5c26faa06b78e77c9bdbbed72852263192c => generated 412 bytes in 544 msecs (HTTP/1.1 200) 1 headers in 59 bytes (2 switches on core 0)
['1753'] s 1753
device_id=f8:a4:5f:11:21:79index=1is_change=0route_id=1753timestamp=2016-03-31 15:39:02type=0client_credentialsf8:a4:5f:11:21:79
[pid: 22319|app: 0|req: 2/2] 140.207.54.77 () {42 vars in 931 bytes} [Thu Jun 16 15:34:55 2016] POST /functiontest?signature=955707ea8002fe4ec9ffad44544efd32304b31d9&timestamp=1466062495&nonce=941929163&openid=oNqycwWK96VhQHx5eM0rBzaUrfZ4&encrypt_type=aes&msg_signature=3d0513d03020f1fec3d041a420e5d47cdd8acc97 => generated 1165 bytes in 184 msecs (HTTP/1.1 200) 1 headers in 59 bytes (2 switches on core 0)
['1753', '36'] r 1753 36
bus_num=9999device_id=f8:a4:5f:11:21:79index=36route_id=1753show_all=1timestamp=2016-03-31 15:39:08client_credentialsf8:a4:5f:11:21:79
[pid: 22319|app: 0|req: 3/3] 140.207.54.77 () {42 vars in 931 bytes} [Thu Jun 16 15:35:00 2016] POST /functiontest?signature=1050c15a99b128dc66f850b7e723c57e9bc4b3a1&timestamp=1466062500&nonce=777779003&openid=oNqycwWK96VhQHx5eM0rBzaUrfZ4&encrypt_type=aes&msg_signature=f95131d7e11cefcf852fef5644f801df090a4ba7 => generated 912 bytes in 4335 msecs (HTTP/1.1 200) 1 headers in 59 bytes (2 switches on core 0)
['592'] 592
device_id=f8:a4:5f:11:21:79is_exact=0keywords=592timestamp=2016-03-31 15:39:00client_credentialsf8:a4:5f:11:21:79
OrderedDict([('device_id', 'f8:a4:5f:11:21:79'), ('is_exact', 0), ('keywords', '592'), ('timestamp', '2016-03-31 15:39:00')]) 5cdaffd38ae86fa639063302fe475477
device_id=f8:a4:5f:11:21:79index=1is_change=0route_id=1429timestamp=2016-03-31 15:39:02type=0client_credentialsf8:a4:5f:11:21:79
device_id=f8:a4:5f:11:21:79index=1is_change=1route_id=1429timestamp=2016-03-31 15:39:02type=0client_credentialsf8:a4:5f:11:21:79
$$$$$$$$$$$$$$$$$bus$$$$$$$$$$$$$$$$ {u'1429': u'\u65b0\u90fd\u4e1c\u7ad9 \u81f3 \u4e1c\u5317\u65fa\u4e2d\u8def', u'1871': u'\u4e1c\u5317\u65fa\u4e2d\u8def \u81f3 \u65b0\u90fd\u4e1c\u7ad9'}
################nginxmonitor################## {"1429": "\u65b0\u90fd\u4e1c\u7ad9 \u81f3 \u4e1c\u5317\u65fa\u4e2d\u8def", "1871": "\u4e1c\u5317\u65fa\u4e2d\u8def \u81f3 \u65b0\u90fd\u4e1c\u7ad9"}
[pid: 22319|app: 0|req: 4/4] 140.207.54.77 () {42 vars in 933 bytes} [Thu Jun 16 15:42:49 2016] POST /functiontest?signature=6ebf9e294f880ca512e23934dbb09be74d991468&timestamp=1466062969&nonce=1600773587&openid=oNqycwWK96VhQHx5eM0rBzaUrfZ4&encrypt_type=aes&msg_signature=bc43fdb5e743e177038fa43de38a723b0f9479a4 => generated 412 bytes in 496 msecs (HTTP/1.1 200) 1 headers in 59 bytes (2 switches on core 0)
['1429'] s 1429
device_id=f8:a4:5f:11:21:79index=1is_change=0route_id=1429timestamp=2016-03-31 15:39:02type=0client_credentialsf8:a4:5f:11:21:79
[pid: 22319|app: 0|req: 5/5] 140.207.54.77 () {42 vars in 931 bytes} [Thu Jun 16 15:43:05 2016] POST /functiontest?signature=c91e4ba0cc2713b33094ff5cbbe4065eb2a392d6&timestamp=1466062985&nonce=340289712&openid=oNqycwWK96VhQHx5eM0rBzaUrfZ4&encrypt_type=aes&msg_signature=271e9d7fccdfaaf09db89d681c48a11086578f4a => generated 588 bytes in 157 msecs (HTTP/1.1 200) 1 headers in 59 bytes (2 switches on core 0)
['1429', '6'] r 1429 6
bus_num=9999device_id=f8:a4:5f:11:21:79index=6route_id=1429show_all=1timestamp=2016-03-31 15:39:08client_credentialsf8:a4:5f:11:21:79
[pid: 22319|app: 0|req: 6/6] 140.207.54.77 () {42 vars in 931 bytes} [Thu Jun 16 15:43:15 2016] POST /functiontest?signature=dbf2341936addde68340840e1407ba0a67c0c260&timestamp=1466062995&nonce=827457566&openid=oNqycwWK96VhQHx5eM0rBzaUrfZ4&encrypt_type=aes&msg_signature=dfc1215e98b42376f97bf5e2fdee47b02dea9e42 => generated 341 bytes in 4329 msecs (HTTP/1.1 200) 1 headers in 59 bytes (2 switches on core 0)
['379'] 379
device_id=f8:a4:5f:11:21:79is_exact=0keywords=379timestamp=2016-03-31 15:39:00client_credentialsf8:a4:5f:11:21:79
OrderedDict([('device_id', 'f8:a4:5f:11:21:79'), ('is_exact', 0), ('keywords', '379'), ('timestamp', '2016-03-31 15:39:00')]) 720e3a7cd5069ec750aa630fe0cb5539
device_id=f8:a4:5f:11:21:79index=1is_change=0route_id=593timestamp=2016-03-31 15:39:02type=0client_credentialsf8:a4:5f:11:21:79
device_id=f8:a4:5f:11:21:79index=1is_change=1route_id=593timestamp=2016-03-31 15:39:02type=0client_credentialsf8:a4:5f:11:21:79
$$$$$$$$$$$$$$$$$bus$$$$$$$$$$$$$$$$ {u'593': u'\u80b2\u65b0\u5c0f\u533a \u81f3 \u5de6\u5bb6\u5e84', u'594': u'\u5de6\u5bb6\u5e84 \u81f3 \u80b2\u65b0\u5c0f\u533a'}
################nginxmonitor################## {"593": "\u80b2\u65b0\u5c0f\u533a \u81f3 \u5de6\u5bb6\u5e84", "594": "\u5de6\u5bb6\u5e84 \u81f3 \u80b2\u65b0\u5c0f\u533a"}
[pid: 22319|app: 0|req: 7/7] 140.207.54.77 () {42 vars in 933 bytes} [Thu Jun 16 15:46:19 2016] POST /functiontest?signature=5e54048acf158b7cd11a50def6c448781f6a2f8b&timestamp=1466063179&nonce=1103529134&openid=oNqycwWK96VhQHx5eM0rBzaUrfZ4&encrypt_type=aes&msg_signature=da18ef59aac9df89dc3a443edf672575a069788f => generated 398 bytes in 461 msecs (HTTP/1.1 200) 1 headers in 59 bytes (2 switches on core 0)
['594'] s 594
device_id=f8:a4:5f:11:21:79index=1is_change=0route_id=594timestamp=2016-03-31 15:39:02type=0client_credentialsf8:a4:5f:11:21:79
[pid: 22319|app: 0|req: 8/8] 140.207.54.77 () {42 vars in 931 bytes} [Thu Jun 16 15:46:29 2016] POST /functiontest?signature=8dae0809e081dc281ab178d004ab1380705ad9a2&timestamp=1466063189&nonce=957343875&openid=oNqycwWK96VhQHx5eM0rBzaUrfZ4&encrypt_type=aes&msg_signature=56f36fb3868d3b88498b39580a9ee300979d8a6b => generated 771 bytes in 153 msecs (HTTP/1.1 200) 1 headers in 59 bytes (2 switches on core 0)
['594', '17'] r 594 17
bus_num=9999device_id=f8:a4:5f:11:21:79index=17route_id=594show_all=1timestamp=2016-03-31 15:39:08client_credentialsf8:a4:5f:11:21:79
[pid: 22319|app: 0|req: 9/9] 140.207.54.77 () {42 vars in 933 bytes} [Thu Jun 16 15:46:37 2016] POST /functiontest?signature=c58ae51389e44aa7ee12f14762d2d7d39de415e1&timestamp=1466063197&nonce=1630095325&openid=oNqycwWK96VhQHx5eM0rBzaUrfZ4&encrypt_type=aes&msg_signature=6dce8cdf117cb4e37fef582ebeaf2730c06b4b6b => generated 615 bytes in 4327 msecs (HTTP/1.1 200) 1 headers in 59 bytes (2 switches on core 0)
['909'] 909
device_id=f8:a4:5f:11:21:79is_exact=0keywords=909timestamp=2016-03-31 15:39:00client_credentialsf8:a4:5f:11:21:79
OrderedDict([('device_id', 'f8:a4:5f:11:21:79'), ('is_exact', 0), ('keywords', '909'), ('timestamp', '2016-03-31 15:39:00')]) 5ec2820150a9014c4334988bc534191f
device_id=f8:a4:5f:11:21:79index=1is_change=0route_id=1753timestamp=2016-03-31 15:39:02type=0client_credentialsf8:a4:5f:11:21:79
device_id=f8:a4:5f:11:21:79index=1is_change=1route_id=1753timestamp=2016-03-31 15:39:02type=0client_credentialsf8:a4:5f:11:21:79
$$$$$$$$$$$$$$$$$bus$$$$$$$$$$$$$$$$ {u'1753': u'\u957f\u5efa\u9a7e\u6821 \u81f3 \u571f\u4e95\u6751\u897f\u53e3', u'2049': u'\u571f\u4e95\u6751\u897f\u53e3 \u81f3 \u957f\u5efa\u9a7e\u6821'}
################nginxmonitor################## {"1753": "\u957f\u5efa\u9a7e\u6821 \u81f3 \u571f\u4e95\u6751\u897f\u53e3", "2049": "\u571f\u4e95\u6751\u897f\u53e3 \u81f3 \u957f\u5efa\u9a7e\u6821"}
[pid: 22318|app: 0|req: 1/10] 140.207.54.77 () {42 vars in 933 bytes} [Thu Jun 16 16:05:07 2016] POST /functiontest?signature=9b292055d6119c05cb3635dea3342d5fbc3975a6&timestamp=1466064307&nonce=1390871616&openid=oNqycwWK96VhQHx5eM0rBzaUrfZ4&encrypt_type=aes&msg_signature=7de159f08b729f917425dd6e02447544ad52dcee => generated 412 bytes in 2258 msecs (HTTP/1.1 200) 1 headers in 59 bytes (2 switches on core 0)
Thu Jun 16 16:45:15 2016 - *** /home/dlgao/project/uwsgi.ini has been touched... grace them all !!! ***
...gracefully killing workers...
Gracefully killing worker 1 (pid: 22318)...
Gracefully killing worker 2 (pid: 22319)...
worker 1 buried after 1 seconds
worker 2 buried after 1 seconds
binary reloading uWSGI...
chdir() to /home/dlgao/project
closing all non-uwsgi socket fds > 2 (max_fd = 131072)...
found fd 3 mapped to socket 0 (10.160.156.96:9102)
running /usr/bin/uwsgi
[uWSGI] getting INI configuration from uwsgi.ini
open("./python_plugin.so"): No such file or directory [core/utils.c line 3675]
!!! UNABLE to load uWSGI plugin: ./python_plugin.so: cannot open shared object file: No such file or directory !!!
*** Starting uWSGI 2.0.11.1 (64bit) on [Thu Jun 16 16:45:16 2016] ***
compiled with version: 4.8.3 20140911 (Red Hat 4.8.3-9) on 20 August 2015 15:10:12
os: Linux-3.10.0-327.4.4.el7.x86_64 #1 SMP Thu Dec 17 15:51:24 EST 2015
nodename: hz-10-160-156-96.internal.lede.com
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 4
current working directory: /home/dlgao/project
detected binary path: /usr/bin/uwsgi
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /home/dlgao/project
your processes number limit is 31147
your memory page size is 4096 bytes
detected max file descriptor number: 131072
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 inherited INET address 10.160.156.96:9102 fd 3
Python version: 2.7.5 (default, Oct 11 2015, 17:47:16)  [GCC 4.8.3 20140911 (Red Hat 4.8.3-9)]
Python main interpreter initialized at 0x8c4030
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 218304 bytes (213 KB) for 2 cores
*** Operational MODE: preforking ***
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x8c4030 pid: 22317 (default app)
*** uWSGI is running in multiple interpreter mode ***
gracefully (RE)spawned uWSGI master process (pid: 22317)
spawned uWSGI worker 1 (pid: 23233, cores: 1)
spawned uWSGI worker 2 (pid: 23234, cores: 1)
['909'] 909
device_id=f8:a4:5f:11:21:79is_exact=0keywords=909timestamp=2016-03-31 15:39:00client_credentialsf8:a4:5f:11:21:79
OrderedDict([('device_id', 'f8:a4:5f:11:21:79'), ('is_exact', 0), ('keywords', '909'), ('timestamp', '2016-03-31 15:39:00')]) 5ec2820150a9014c4334988bc534191f
device_id=f8:a4:5f:11:21:79index=1is_change=0route_id=1753timestamp=2016-03-31 15:39:02type=0client_credentialsf8:a4:5f:11:21:79
device_id=f8:a4:5f:11:21:79index=1is_change=1route_id=1753timestamp=2016-03-31 15:39:02type=0client_credentialsf8:a4:5f:11:21:79
$$$$$$$$$$$$$$$$$bus$$$$$$$$$$$$$$$$ {u'1753': u'\u957f\u5efa\u9a7e\u6821 \u81f3 \u571f\u4e95\u6751\u897f\u53e3', u'2049': u'\u571f\u4e95\u6751\u897f\u53e3 \u81f3 \u957f\u5efa\u9a7e\u6821'}
################nginxmonitor################## {"1753": "\u957f\u5efa\u9a7e\u6821 \u81f3 \u571f\u4e95\u6751\u897f\u53e3", "2049": "\u571f\u4e95\u6751\u897f\u53e3 \u81f3 \u957f\u5efa\u9a7e\u6821"}
oNqycwWK96VhQHx5eM0rBzaUrfZ4 gh_ebb0ceaa639e
[pid: 23233|app: 0|req: 1/1] 140.207.54.77 () {42 vars in 931 bytes} [Thu Jun 16 16:45:25 2016] POST /functiontest?signature=1149cdf14967a6f31602d57fc28f71f7f3860f35&timestamp=1466066725&nonce=236936687&openid=oNqycwWK96VhQHx5eM0rBzaUrfZ4&encrypt_type=aes&msg_signature=69bf43dbb6450ab8682b0b823c112b3b2ae555cd => generated 412 bytes in 1862 msecs (HTTP/1.1 200) 1 headers in 59 bytes (2 switches on core 0)
Thu Jun 16 17:07:31 2016 - *** /home/dlgao/project/uwsgi.ini has been touched... grace them all !!! ***
...gracefully killing workers...
Gracefully killing worker 1 (pid: 23233)...
Gracefully killing worker 2 (pid: 23234)...
worker 1 buried after 1 seconds
worker 2 buried after 1 seconds
binary reloading uWSGI...
chdir() to /home/dlgao/project
closing all non-uwsgi socket fds > 2 (max_fd = 131072)...
found fd 3 mapped to socket 0 (10.160.156.96:9102)
running /usr/bin/uwsgi
[uWSGI] getting INI configuration from uwsgi.ini
open("./python_plugin.so"): No such file or directory [core/utils.c line 3675]
!!! UNABLE to load uWSGI plugin: ./python_plugin.so: cannot open shared object file: No such file or directory !!!
*** Starting uWSGI 2.0.11.1 (64bit) on [Thu Jun 16 17:07:32 2016] ***
compiled with version: 4.8.3 20140911 (Red Hat 4.8.3-9) on 20 August 2015 15:10:12
os: Linux-3.10.0-327.4.4.el7.x86_64 #1 SMP Thu Dec 17 15:51:24 EST 2015
nodename: hz-10-160-156-96.internal.lede.com
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 4
current working directory: /home/dlgao/project
detected binary path: /usr/bin/uwsgi
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /home/dlgao/project
your processes number limit is 31147
your memory page size is 4096 bytes
detected max file descriptor number: 131072
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 inherited INET address 10.160.156.96:9102 fd 3
Python version: 2.7.5 (default, Oct 11 2015, 17:47:16)  [GCC 4.8.3 20140911 (Red Hat 4.8.3-9)]
Python main interpreter initialized at 0x1522030
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 218304 bytes (213 KB) for 2 cores
*** Operational MODE: preforking ***
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x1522030 pid: 22317 (default app)
*** uWSGI is running in multiple interpreter mode ***
gracefully (RE)spawned uWSGI master process (pid: 22317)
spawned uWSGI worker 1 (pid: 23504, cores: 1)
spawned uWSGI worker 2 (pid: 23505, cores: 1)
[] xxx
oNqycwWK96VhQHx5eM0rBzaUrfZ4 gh_ebb0ceaa639e
[pid: 23504|app: 0|req: 1/1] 140.207.54.77 () {42 vars in 931 bytes} [Thu Jun 16 17:07:40 2016] POST /functiontest?signature=bc00c8e1a130992dfbfceecce5da0af6c94f377d&timestamp=1466068060&nonce=391834273&openid=oNqycwWK96VhQHx5eM0rBzaUrfZ4&encrypt_type=aes&msg_signature=a6c0edf415dcd48b429c18115756c27bc55d266d => generated 336 bytes in 65 msecs (HTTP/1.1 200) 1 headers in 59 bytes (2 switches on core 0)
Thu Jun 16 17:46:14 2016 - *** /home/dlgao/project/uwsgi.ini has been touched... grace them all !!! ***
...gracefully killing workers...
Gracefully killing worker 1 (pid: 23504)...
Gracefully killing worker 2 (pid: 23505)...
worker 1 buried after 1 seconds
worker 2 buried after 1 seconds
binary reloading uWSGI...
chdir() to /home/dlgao/project
closing all non-uwsgi socket fds > 2 (max_fd = 131072)...
found fd 3 mapped to socket 0 (10.160.156.96:9102)
running /usr/bin/uwsgi
[uWSGI] getting INI configuration from uwsgi.ini
open("./python_plugin.so"): No such file or directory [core/utils.c line 3675]
!!! UNABLE to load uWSGI plugin: ./python_plugin.so: cannot open shared object file: No such file or directory !!!
*** Starting uWSGI 2.0.11.1 (64bit) on [Thu Jun 16 17:46:15 2016] ***
compiled with version: 4.8.3 20140911 (Red Hat 4.8.3-9) on 20 August 2015 15:10:12
os: Linux-3.10.0-327.4.4.el7.x86_64 #1 SMP Thu Dec 17 15:51:24 EST 2015
nodename: hz-10-160-156-96.internal.lede.com
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 4
current working directory: /home/dlgao/project
detected binary path: /usr/bin/uwsgi
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /home/dlgao/project
your processes number limit is 31147
your memory page size is 4096 bytes
detected max file descriptor number: 131072
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 inherited INET address 10.160.156.96:9102 fd 3
Python version: 2.7.5 (default, Oct 11 2015, 17:47:16)  [GCC 4.8.3 20140911 (Red Hat 4.8.3-9)]
Python main interpreter initialized at 0x1f37030
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 218304 bytes (213 KB) for 2 cores
*** Operational MODE: preforking ***
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x1f37030 pid: 22317 (default app)
*** uWSGI is running in multiple interpreter mode ***
gracefully (RE)spawned uWSGI master process (pid: 22317)
spawned uWSGI worker 1 (pid: 24090, cores: 1)
spawned uWSGI worker 2 (pid: 24091, cores: 1)
['909'] 909
device_id=f8:a4:5f:11:21:79is_exact=0keywords=909timestamp=2016-03-31 15:39:00client_credentialsf8:a4:5f:11:21:79
OrderedDict([('device_id', 'f8:a4:5f:11:21:79'), ('is_exact', 0), ('keywords', '909'), ('timestamp', '2016-03-31 15:39:00')]) 5ec2820150a9014c4334988bc534191f
device_id=f8:a4:5f:11:21:79index=1is_change=0route_id=1753timestamp=2016-03-31 15:39:02type=0client_credentialsf8:a4:5f:11:21:79
device_id=f8:a4:5f:11:21:79index=1is_change=1route_id=1753timestamp=2016-03-31 15:39:02type=0client_credentialsf8:a4:5f:11:21:79
$$$$$$$$$$$$$$$$$bus$$$$$$$$$$$$$$$$ {u'1753': u'\u957f\u5efa\u9a7e\u6821 \u81f3 \u571f\u4e95\u6751\u897f\u53e3', u'2049': u'\u571f\u4e95\u6751\u897f\u53e3 \u81f3 \u957f\u5efa\u9a7e\u6821'}
################nginxmonitor################## {"1753": "\u957f\u5efa\u9a7e\u6821 \u81f3 \u571f\u4e95\u6751\u897f\u53e3", "2049": "\u571f\u4e95\u6751\u897f\u53e3 \u81f3 \u957f\u5efa\u9a7e\u6821"}
oNqycwWK96VhQHx5eM0rBzaUrfZ4 gh_ebb0ceaa639e
[pid: 24090|app: 0|req: 1/1] 140.207.54.77 () {42 vars in 931 bytes} [Thu Jun 16 17:46:23 2016] POST /functiontest?signature=36232385be676db3c8c628d0047200ed0a2d7e65&timestamp=1466070383&nonce=245346251&openid=oNqycwWK96VhQHx5eM0rBzaUrfZ4&encrypt_type=aes&msg_signature=a77e213fc9ea62e37697540e3ad30538eecf626b => generated 415 bytes in 2380 msecs (HTTP/1.1 200) 1 headers in 59 bytes (2 switches on core 0)
['1753'] r 1753
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/web.py-0.37-py2.7.egg/web/application.py", line 239, in process
    return self.handle()
  File "/usr/lib/python2.7/site-packages/web.py-0.37-py2.7.egg/web/application.py", line 230, in handle
    return self._delegate(fn, self.fvars, args)
  File "/usr/lib/python2.7/site-packages/web.py-0.37-py2.7.egg/web/application.py", line 420, in _delegate
    return handle_class(cls)
  File "/usr/lib/python2.7/site-packages/web.py-0.37-py2.7.egg/web/application.py", line 396, in handle_class
    return tocall(*args)
  File "./app/controllers/nginxmonitor.py", line 64, in POST
    busId  = int(keyWord)
ValueError: invalid literal for int() with base 10: 'r 1753'

[pid: 24090|app: 0|req: 2/2] 140.207.54.77 () {42 vars in 929 bytes} [Thu Jun 16 17:46:37 2016] POST /functiontest?signature=08748ada69412fdc3822f987a0ad2d84f2fadfe6&timestamp=1466070397&nonce=62698161&openid=oNqycwWK96VhQHx5eM0rBzaUrfZ4&encrypt_type=aes&msg_signature=fc1dcd95c9efdbbf243b7e7c4c1100fca0598a6c => generated 37272 bytes in 56 msecs (HTTP/1.1 500) 1 headers in 63 bytes (2 switches on core 0)
['1753'] r 1753
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/web.py-0.37-py2.7.egg/web/application.py", line 239, in process
    return self.handle()
  File "/usr/lib/python2.7/site-packages/web.py-0.37-py2.7.egg/web/application.py", line 230, in handle
    return self._delegate(fn, self.fvars, args)
  File "/usr/lib/python2.7/site-packages/web.py-0.37-py2.7.egg/web/application.py", line 420, in _delegate
    return handle_class(cls)
  File "/usr/lib/python2.7/site-packages/web.py-0.37-py2.7.egg/web/application.py", line 396, in handle_class
    return tocall(*args)
  File "./app/controllers/nginxmonitor.py", line 64, in POST
    busId  = int(keyWord)
ValueError: invalid literal for int() with base 10: 'r 1753'

[pid: 24091|app: 0|req: 1/3] 140.207.54.77 () {42 vars in 933 bytes} [Thu Jun 16 17:46:47 2016] POST /functiontest?signature=9d89097eeb91111ccd0ff1549c007ec94a32e2c8&timestamp=1466070407&nonce=2015267319&openid=oNqycwWK96VhQHx5eM0rBzaUrfZ4&encrypt_type=aes&msg_signature=48d34ab0b4062754aa07143bd3894a744e76818f => generated 37288 bytes in 111 msecs (HTTP/1.1 500) 1 headers in 63 bytes (2 switches on core 0)
['1753'] r 1753
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/web.py-0.37-py2.7.egg/web/application.py", line 239, in process
    return self.handle()
  File "/usr/lib/python2.7/site-packages/web.py-0.37-py2.7.egg/web/application.py", line 230, in handle
    return self._delegate(fn, self.fvars, args)
  File "/usr/lib/python2.7/site-packages/web.py-0.37-py2.7.egg/web/application.py", line 420, in _delegate
    return handle_class(cls)
  File "/usr/lib/python2.7/site-packages/web.py-0.37-py2.7.egg/web/application.py", line 396, in handle_class
    return tocall(*args)
  File "./app/controllers/nginxmonitor.py", line 64, in POST
    busId  = int(keyWord)
ValueError: invalid literal for int() with base 10: 'r 1753'

[pid: 24090|app: 0|req: 3/4] 140.207.54.77 () {42 vars in 933 bytes} [Thu Jun 16 17:46:57 2016] POST /functiontest?signature=b6b0e8a585cb05e3cd46032504b94cc156f15fbb&timestamp=1466070417&nonce=1147814279&openid=oNqycwWK96VhQHx5eM0rBzaUrfZ4&encrypt_type=aes&msg_signature=39f1e9902cf7f70e736b868cf5530b4c0adfde3b => generated 37980 bytes in 14 msecs (HTTP/1.1 500) 1 headers in 63 bytes (2 switches on core 0)
Thu Jun 16 17:47:25 2016 - *** /home/dlgao/project/uwsgi.ini has been touched... grace them all !!! ***
...gracefully killing workers...
Gracefully killing worker 1 (pid: 24090)...
Gracefully killing worker 2 (pid: 24091)...
worker 1 buried after 1 seconds
worker 2 buried after 1 seconds
binary reloading uWSGI...
chdir() to /home/dlgao/project
closing all non-uwsgi socket fds > 2 (max_fd = 131072)...
found fd 3 mapped to socket 0 (10.160.156.96:9102)
running /usr/bin/uwsgi
[uWSGI] getting INI configuration from uwsgi.ini
open("./python_plugin.so"): No such file or directory [core/utils.c line 3675]
!!! UNABLE to load uWSGI plugin: ./python_plugin.so: cannot open shared object file: No such file or directory !!!
*** Starting uWSGI 2.0.11.1 (64bit) on [Thu Jun 16 17:47:26 2016] ***
compiled with version: 4.8.3 20140911 (Red Hat 4.8.3-9) on 20 August 2015 15:10:12
os: Linux-3.10.0-327.4.4.el7.x86_64 #1 SMP Thu Dec 17 15:51:24 EST 2015
nodename: hz-10-160-156-96.internal.lede.com
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 4
current working directory: /home/dlgao/project
detected binary path: /usr/bin/uwsgi
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /home/dlgao/project
your processes number limit is 31147
your memory page size is 4096 bytes
detected max file descriptor number: 131072
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 inherited INET address 10.160.156.96:9102 fd 3
Python version: 2.7.5 (default, Oct 11 2015, 17:47:16)  [GCC 4.8.3 20140911 (Red Hat 4.8.3-9)]
Python main interpreter initialized at 0x2675030
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 218304 bytes (213 KB) for 2 cores
*** Operational MODE: preforking ***
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x2675030 pid: 22317 (default app)
*** uWSGI is running in multiple interpreter mode ***
gracefully (RE)spawned uWSGI master process (pid: 22317)
spawned uWSGI worker 1 (pid: 24114, cores: 1)
spawned uWSGI worker 2 (pid: 24115, cores: 1)
['909'] 909
device_id=f8:a4:5f:11:21:79index=1is_change=0route_id=909timestamp=2016-03-31 15:39:02type=0client_credentialsf8:a4:5f:11:21:79
oNqycwWK96VhQHx5eM0rBzaUrfZ4 gh_ebb0ceaa639e
[pid: 24115|app: 0|req: 1/1] 140.207.54.77 () {42 vars in 933 bytes} [Thu Jun 16 17:47:38 2016] POST /functiontest?signature=925ec14b7340b8205cb95552ea622046221b0e44&timestamp=1466070458&nonce=1750085184&openid=oNqycwWK96VhQHx5eM0rBzaUrfZ4&encrypt_type=aes&msg_signature=2a9c49e80d19a1eaba6c664d30768eb55756af29 => generated 927 bytes in 247 msecs (HTTP/1.1 200) 1 headers in 59 bytes (2 switches on core 0)
['909'] 909
device_id=f8:a4:5f:11:21:79is_exact=0keywords=909timestamp=2016-03-31 15:39:00client_credentialsf8:a4:5f:11:21:79
OrderedDict([('device_id', 'f8:a4:5f:11:21:79'), ('is_exact', 0), ('keywords', '909'), ('timestamp', '2016-03-31 15:39:00')]) 5ec2820150a9014c4334988bc534191f
device_id=f8:a4:5f:11:21:79index=1is_change=0route_id=1753timestamp=2016-03-31 15:39:02type=0client_credentialsf8:a4:5f:11:21:79
device_id=f8:a4:5f:11:21:79index=1is_change=1route_id=1753timestamp=2016-03-31 15:39:02type=0client_credentialsf8:a4:5f:11:21:79
$$$$$$$$$$$$$$$$$bus$$$$$$$$$$$$$$$$ {u'1753': u'\u957f\u5efa\u9a7e\u6821 \u81f3 \u571f\u4e95\u6751\u897f\u53e3', u'2049': u'\u571f\u4e95\u6751\u897f\u53e3 \u81f3 \u957f\u5efa\u9a7e\u6821'}
################nginxmonitor################## {"1753": "\u957f\u5efa\u9a7e\u6821 \u81f3 \u571f\u4e95\u6751\u897f\u53e3", "2049": "\u571f\u4e95\u6751\u897f\u53e3 \u81f3 \u957f\u5efa\u9a7e\u6821"}
oNqycwWK96VhQHx5eM0rBzaUrfZ4 gh_ebb0ceaa639e
[pid: 24115|app: 0|req: 2/2] 140.207.54.77 () {42 vars in 931 bytes} [Thu Jun 16 17:48:56 2016] POST /functiontest?signature=f791b32d045c3ccfb23dec22be580bdbdc9f8ff5&timestamp=1466070536&nonce=552178553&openid=oNqycwWK96VhQHx5eM0rBzaUrfZ4&encrypt_type=aes&msg_signature=368fc3fa48874585b394eeef972c039b96513313 => generated 415 bytes in 438 msecs (HTTP/1.1 200) 1 headers in 59 bytes (2 switches on core 0)
['1753'] r 1753
oNqycwWK96VhQHx5eM0rBzaUrfZ4 gh_ebb0ceaa639e
[pid: 24115|app: 0|req: 3/3] 140.207.54.77 () {42 vars in 931 bytes} [Thu Jun 16 17:49:03 2016] POST /functiontest?signature=ba400bad6a1216ed2a7a2263b9c10a041ae45aed&timestamp=1466070543&nonce=419331288&openid=oNqycwWK96VhQHx5eM0rBzaUrfZ4&encrypt_type=aes&msg_signature=1b83c6da43d11f40675eda140264d82669613811 => generated 280 bytes in 7 msecs (HTTP/1.1 200) 1 headers in 59 bytes (2 switches on core 0)
['34'] 34
device_id=f8:a4:5f:11:21:79index=1is_change=0route_id=34timestamp=2016-03-31 15:39:02type=0client_credentialsf8:a4:5f:11:21:79
oNqycwWK96VhQHx5eM0rBzaUrfZ4 gh_ebb0ceaa639e
[pid: 24115|app: 0|req: 4/4] 140.207.54.77 () {42 vars in 933 bytes} [Thu Jun 16 17:49:15 2016] POST /functiontest?signature=6e18727620bdf1323263f46c2f4b0111d93423e0&timestamp=1466070555&nonce=1771906314&openid=oNqycwWK96VhQHx5eM0rBzaUrfZ4&encrypt_type=aes&msg_signature=87f9c92493f096f78d029bd783c6d36134c6af9f => generated 937 bytes in 149 msecs (HTTP/1.1 200) 1 headers in 59 bytes (2 switches on core 0)
Thu Jun 16 17:50:58 2016 - *** /home/dlgao/project/uwsgi.ini has been touched... grace them all !!! ***
...gracefully killing workers...
Gracefully killing worker 2 (pid: 24115)...
Gracefully killing worker 1 (pid: 24114)...
worker 1 buried after 1 seconds
worker 2 buried after 1 seconds
binary reloading uWSGI...
chdir() to /home/dlgao/project
closing all non-uwsgi socket fds > 2 (max_fd = 131072)...
found fd 3 mapped to socket 0 (10.160.156.96:9102)
running /usr/bin/uwsgi
[uWSGI] getting INI configuration from uwsgi.ini
open("./python_plugin.so"): No such file or directory [core/utils.c line 3675]
!!! UNABLE to load uWSGI plugin: ./python_plugin.so: cannot open shared object file: No such file or directory !!!
*** Starting uWSGI 2.0.11.1 (64bit) on [Thu Jun 16 17:50:59 2016] ***
compiled with version: 4.8.3 20140911 (Red Hat 4.8.3-9) on 20 August 2015 15:10:12
os: Linux-3.10.0-327.4.4.el7.x86_64 #1 SMP Thu Dec 17 15:51:24 EST 2015
nodename: hz-10-160-156-96.internal.lede.com
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 4
current working directory: /home/dlgao/project
detected binary path: /usr/bin/uwsgi
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /home/dlgao/project
your processes number limit is 31147
your memory page size is 4096 bytes
detected max file descriptor number: 131072
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 inherited INET address 10.160.156.96:9102 fd 3
Python version: 2.7.5 (default, Oct 11 2015, 17:47:16)  [GCC 4.8.3 20140911 (Red Hat 4.8.3-9)]
Python main interpreter initialized at 0x105a030
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 218304 bytes (213 KB) for 2 cores
*** Operational MODE: preforking ***
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x105a030 pid: 22317 (default app)
*** uWSGI is running in multiple interpreter mode ***
gracefully (RE)spawned uWSGI master process (pid: 22317)
spawned uWSGI worker 1 (pid: 24177, cores: 1)
spawned uWSGI worker 2 (pid: 24178, cores: 1)
['909'] 909
device_id=f8:a4:5f:11:21:79is_exact=0keywords=909timestamp=2016-03-31 15:39:00client_credentialsf8:a4:5f:11:21:79
OrderedDict([('device_id', 'f8:a4:5f:11:21:79'), ('is_exact', 0), ('keywords', '909'), ('timestamp', '2016-03-31 15:39:00')]) 5ec2820150a9014c4334988bc534191f
device_id=f8:a4:5f:11:21:79index=1is_change=0route_id=1753timestamp=2016-03-31 15:39:02type=0client_credentialsf8:a4:5f:11:21:79
device_id=f8:a4:5f:11:21:79index=1is_change=1route_id=1753timestamp=2016-03-31 15:39:02type=0client_credentialsf8:a4:5f:11:21:79
$$$$$$$$$$$$$$$$$bus$$$$$$$$$$$$$$$$ {u'1753': u'\u957f\u5efa\u9a7e\u6821 \u81f3 \u571f\u4e95\u6751\u897f\u53e3', u'2049': u'\u571f\u4e95\u6751\u897f\u53e3 \u81f3 \u957f\u5efa\u9a7e\u6821'}
oNqycwWK96VhQHx5eM0rBzaUrfZ4 gh_ebb0ceaa639e
[pid: 24177|app: 0|req: 1/1] 140.207.54.77 () {42 vars in 931 bytes} [Thu Jun 16 17:51:06 2016] POST /functiontest?signature=9f572339f75515c3228a976f32e70a206071c1ad&timestamp=1466070666&nonce=852053142&openid=oNqycwWK96VhQHx5eM0rBzaUrfZ4&encrypt_type=aes&msg_signature=a0e798165321cf2d510b7fa3bf961695f5b6f4f5 => generated 415 bytes in 658 msecs (HTTP/1.1 200) 1 headers in 59 bytes (2 switches on core 0)
Thu Jun 16 17:53:27 2016 - *** /home/dlgao/project/uwsgi.ini has been touched... grace them all !!! ***
...gracefully killing workers...
Gracefully killing worker 1 (pid: 24177)...
Gracefully killing worker 2 (pid: 24178)...
worker 1 buried after 1 seconds
worker 2 buried after 1 seconds
binary reloading uWSGI...
chdir() to /home/dlgao/project
closing all non-uwsgi socket fds > 2 (max_fd = 131072)...
found fd 3 mapped to socket 0 (10.160.156.96:9102)
running /usr/bin/uwsgi
[uWSGI] getting INI configuration from uwsgi.ini
open("./python_plugin.so"): No such file or directory [core/utils.c line 3675]
!!! UNABLE to load uWSGI plugin: ./python_plugin.so: cannot open shared object file: No such file or directory !!!
*** Starting uWSGI 2.0.11.1 (64bit) on [Thu Jun 16 17:53:28 2016] ***
compiled with version: 4.8.3 20140911 (Red Hat 4.8.3-9) on 20 August 2015 15:10:12
os: Linux-3.10.0-327.4.4.el7.x86_64 #1 SMP Thu Dec 17 15:51:24 EST 2015
nodename: hz-10-160-156-96.internal.lede.com
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 4
current working directory: /home/dlgao/project
detected binary path: /usr/bin/uwsgi
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /home/dlgao/project
your processes number limit is 31147
your memory page size is 4096 bytes
detected max file descriptor number: 131072
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 inherited INET address 10.160.156.96:9102 fd 3
Python version: 2.7.5 (default, Oct 11 2015, 17:47:16)  [GCC 4.8.3 20140911 (Red Hat 4.8.3-9)]
Python main interpreter initialized at 0x16ea030
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 218304 bytes (213 KB) for 2 cores
*** Operational MODE: preforking ***
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x16ea030 pid: 22317 (default app)
*** uWSGI is running in multiple interpreter mode ***
gracefully (RE)spawned uWSGI master process (pid: 22317)
spawned uWSGI worker 1 (pid: 24194, cores: 1)
spawned uWSGI worker 2 (pid: 24195, cores: 1)
['909'] 909
device_id=f8:a4:5f:11:21:79index=1is_change=0route_id=909timestamp=2016-03-31 15:39:02type=0client_credentialsf8:a4:5f:11:21:79
oNqycwWK96VhQHx5eM0rBzaUrfZ4 gh_ebb0ceaa639e
[pid: 24194|app: 0|req: 1/1] 140.207.54.77 () {42 vars in 933 bytes} [Thu Jun 16 17:53:35 2016] POST /functiontest?signature=aa0d262814ec3bd76d333f7b92f6b6fd96eb6d6c&timestamp=1466070814&nonce=1840652154&openid=oNqycwWK96VhQHx5eM0rBzaUrfZ4&encrypt_type=aes&msg_signature=f182542044e743c68dd01cab40de5d7726b8418c => generated 927 bytes in 277 msecs (HTTP/1.1 200) 1 headers in 59 bytes (2 switches on core 0)
Thu Jun 16 17:54:33 2016 - *** /home/dlgao/project/uwsgi.ini has been touched... grace them all !!! ***
...gracefully killing workers...
Gracefully killing worker 2 (pid: 24195)...
Gracefully killing worker 1 (pid: 24194)...
worker 1 buried after 1 seconds
worker 2 buried after 1 seconds
binary reloading uWSGI...
chdir() to /home/dlgao/project
closing all non-uwsgi socket fds > 2 (max_fd = 131072)...
found fd 3 mapped to socket 0 (10.160.156.96:9102)
running /usr/bin/uwsgi
[uWSGI] getting INI configuration from uwsgi.ini
open("./python_plugin.so"): No such file or directory [core/utils.c line 3675]
!!! UNABLE to load uWSGI plugin: ./python_plugin.so: cannot open shared object file: No such file or directory !!!
*** Starting uWSGI 2.0.11.1 (64bit) on [Thu Jun 16 17:54:34 2016] ***
compiled with version: 4.8.3 20140911 (Red Hat 4.8.3-9) on 20 August 2015 15:10:12
os: Linux-3.10.0-327.4.4.el7.x86_64 #1 SMP Thu Dec 17 15:51:24 EST 2015
nodename: hz-10-160-156-96.internal.lede.com
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 4
current working directory: /home/dlgao/project
detected binary path: /usr/bin/uwsgi
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /home/dlgao/project
your processes number limit is 31147
your memory page size is 4096 bytes
detected max file descriptor number: 131072
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 inherited INET address 10.160.156.96:9102 fd 3
Python version: 2.7.5 (default, Oct 11 2015, 17:47:16)  [GCC 4.8.3 20140911 (Red Hat 4.8.3-9)]
Python main interpreter initialized at 0x2210030
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 218304 bytes (213 KB) for 2 cores
*** Operational MODE: preforking ***
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x2210030 pid: 22317 (default app)
*** uWSGI is running in multiple interpreter mode ***
gracefully (RE)spawned uWSGI master process (pid: 22317)
spawned uWSGI worker 1 (pid: 24209, cores: 1)
spawned uWSGI worker 2 (pid: 24210, cores: 1)
['909'] 909
device_id=f8:a4:5f:11:21:79is_exact=0keywords=909timestamp=2016-03-31 15:39:00client_credentialsf8:a4:5f:11:21:79
OrderedDict([('device_id', 'f8:a4:5f:11:21:79'), ('is_exact', 0), ('keywords', '909'), ('timestamp', '2016-03-31 15:39:00')]) 5ec2820150a9014c4334988bc534191f
device_id=f8:a4:5f:11:21:79index=1is_change=0route_id=1753timestamp=2016-03-31 15:39:02type=0client_credentialsf8:a4:5f:11:21:79
device_id=f8:a4:5f:11:21:79index=1is_change=1route_id=1753timestamp=2016-03-31 15:39:02type=0client_credentialsf8:a4:5f:11:21:79
$$$$$$$$$$$$$$$$$bus$$$$$$$$$$$$$$$$ {u'1753': u'\u957f\u5efa\u9a7e\u6821 \u81f3 \u571f\u4e95\u6751\u897f\u53e3', u'2049': u'\u571f\u4e95\u6751\u897f\u53e3 \u81f3 \u957f\u5efa\u9a7e\u6821'}
oNqycwWK96VhQHx5eM0rBzaUrfZ4 gh_ebb0ceaa639e
[pid: 24209|app: 0|req: 1/1] 140.207.54.77 () {42 vars in 933 bytes} [Thu Jun 16 17:54:40 2016] POST /functiontest?signature=f128bb3f4d9e56fb0c92fb24df17adaafd12f440&timestamp=1466070880&nonce=1181980109&openid=oNqycwWK96VhQHx5eM0rBzaUrfZ4&encrypt_type=aes&msg_signature=24d1af1ba8af710c89623342d02a0a3c86c3266f => generated 415 bytes in 516 msecs (HTTP/1.1 200) 1 headers in 59 bytes (2 switches on core 0)
['123'] 123
[pid: 24209|app: 0|req: 2/2] 140.207.54.77 () {42 vars in 931 bytes} [Thu Jun 16 17:54:47 2016] POST /functiontest?signature=561cacd984f98688ad77758af706d9060e083245&timestamp=1466070886&nonce=353959347&openid=oNqycwWK96VhQHx5eM0rBzaUrfZ4&encrypt_type=aes&msg_signature=db6cbbb2e65ef0f8d3476c78ae74a5f4128200fc => generated 305 bytes in 8 msecs (HTTP/1.1 200) 1 headers in 59 bytes (2 switches on core 0)
['1753'] 1753
[pid: 24210|app: 0|req: 1/3] 140.207.54.77 () {42 vars in 931 bytes} [Thu Jun 16 17:54:58 2016] POST /functiontest?signature=a169bf96917f39a969c738a0892ef4574b0dbb06&timestamp=1466070898&nonce=850731843&openid=oNqycwWK96VhQHx5eM0rBzaUrfZ4&encrypt_type=aes&msg_signature=5f3a452d595bf37f030d69e6411178b17a8393f0 => generated 305 bytes in 63 msecs (HTTP/1.1 200) 1 headers in 59 bytes (2 switches on core 0)
Thu Jun 16 17:55:21 2016 - *** /home/dlgao/project/uwsgi.ini has been touched... grace them all !!! ***
...gracefully killing workers...
Gracefully killing worker 1 (pid: 24209)...
Gracefully killing worker 2 (pid: 24210)...
worker 1 buried after 1 seconds
worker 2 buried after 1 seconds
binary reloading uWSGI...
chdir() to /home/dlgao/project
closing all non-uwsgi socket fds > 2 (max_fd = 131072)...
found fd 3 mapped to socket 0 (10.160.156.96:9102)
running /usr/bin/uwsgi
[uWSGI] getting INI configuration from uwsgi.ini
open("./python_plugin.so"): No such file or directory [core/utils.c line 3675]
!!! UNABLE to load uWSGI plugin: ./python_plugin.so: cannot open shared object file: No such file or directory !!!
*** Starting uWSGI 2.0.11.1 (64bit) on [Thu Jun 16 17:55:22 2016] ***
compiled with version: 4.8.3 20140911 (Red Hat 4.8.3-9) on 20 August 2015 15:10:12
os: Linux-3.10.0-327.4.4.el7.x86_64 #1 SMP Thu Dec 17 15:51:24 EST 2015
nodename: hz-10-160-156-96.internal.lede.com
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 4
current working directory: /home/dlgao/project
detected binary path: /usr/bin/uwsgi
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /home/dlgao/project
your processes number limit is 31147
your memory page size is 4096 bytes
detected max file descriptor number: 131072
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 inherited INET address 10.160.156.96:9102 fd 3
Python version: 2.7.5 (default, Oct 11 2015, 17:47:16)  [GCC 4.8.3 20140911 (Red Hat 4.8.3-9)]
Python main interpreter initialized at 0x24bd030
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 218304 bytes (213 KB) for 2 cores
*** Operational MODE: preforking ***
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x24bd030 pid: 22317 (default app)
*** uWSGI is running in multiple interpreter mode ***
gracefully (RE)spawned uWSGI master process (pid: 22317)
spawned uWSGI worker 1 (pid: 24234, cores: 1)
spawned uWSGI worker 2 (pid: 24235, cores: 1)
['1'] 1
device_id=f8:a4:5f:11:21:79index=1is_change=0route_id=1timestamp=2016-03-31 15:39:02type=0client_credentialsf8:a4:5f:11:21:79
oNqycwWK96VhQHx5eM0rBzaUrfZ4 gh_ebb0ceaa639e
[pid: 24235|app: 0|req: 1/1] 140.207.54.77 () {42 vars in 929 bytes} [Thu Jun 16 17:55:27 2016] POST /functiontest?signature=e15066ab9beb88965f9735471205301f5f4eefb4&timestamp=1466070926&nonce=14953921&openid=oNqycwWK96VhQHx5eM0rBzaUrfZ4&encrypt_type=aes&msg_signature=842c24366e60fb1887c6c475f2771cef4705ed82 => generated 799 bytes in 216 msecs (HTTP/1.1 200) 1 headers in 59 bytes (2 switches on core 0)
Thu Jun 16 17:55:59 2016 - *** /home/dlgao/project/uwsgi.ini has been touched... grace them all !!! ***
...gracefully killing workers...
Gracefully killing worker 2 (pid: 24235)...
Gracefully killing worker 1 (pid: 24234)...
worker 1 buried after 1 seconds
worker 2 buried after 1 seconds
binary reloading uWSGI...
chdir() to /home/dlgao/project
closing all non-uwsgi socket fds > 2 (max_fd = 131072)...
found fd 3 mapped to socket 0 (10.160.156.96:9102)
running /usr/bin/uwsgi
[uWSGI] getting INI configuration from uwsgi.ini
open("./python_plugin.so"): No such file or directory [core/utils.c line 3675]
!!! UNABLE to load uWSGI plugin: ./python_plugin.so: cannot open shared object file: No such file or directory !!!
*** Starting uWSGI 2.0.11.1 (64bit) on [Thu Jun 16 17:56:00 2016] ***
compiled with version: 4.8.3 20140911 (Red Hat 4.8.3-9) on 20 August 2015 15:10:12
os: Linux-3.10.0-327.4.4.el7.x86_64 #1 SMP Thu Dec 17 15:51:24 EST 2015
nodename: hz-10-160-156-96.internal.lede.com
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 4
current working directory: /home/dlgao/project
detected binary path: /usr/bin/uwsgi
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /home/dlgao/project
your processes number limit is 31147
your memory page size is 4096 bytes
detected max file descriptor number: 131072
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 inherited INET address 10.160.156.96:9102 fd 3
Python version: 2.7.5 (default, Oct 11 2015, 17:47:16)  [GCC 4.8.3 20140911 (Red Hat 4.8.3-9)]
Python main interpreter initialized at 0x252a030
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 218304 bytes (213 KB) for 2 cores
*** Operational MODE: preforking ***
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x252a030 pid: 22317 (default app)
*** uWSGI is running in multiple interpreter mode ***
gracefully (RE)spawned uWSGI master process (pid: 22317)
spawned uWSGI worker 1 (pid: 24267, cores: 1)
spawned uWSGI worker 2 (pid: 24268, cores: 1)
['909'] 909
device_id=f8:a4:5f:11:21:79is_exact=0keywords=909timestamp=2016-03-31 15:39:00client_credentialsf8:a4:5f:11:21:79
OrderedDict([('device_id', 'f8:a4:5f:11:21:79'), ('is_exact', 0), ('keywords', '909'), ('timestamp', '2016-03-31 15:39:00')]) 5ec2820150a9014c4334988bc534191f
device_id=f8:a4:5f:11:21:79index=1is_change=0route_id=1753timestamp=2016-03-31 15:39:02type=0client_credentialsf8:a4:5f:11:21:79
device_id=f8:a4:5f:11:21:79index=1is_change=1route_id=1753timestamp=2016-03-31 15:39:02type=0client_credentialsf8:a4:5f:11:21:79
$$$$$$$$$$$$$$$$$bus$$$$$$$$$$$$$$$$ {u'1753': u'\u957f\u5efa\u9a7e\u6821 \u81f3 \u571f\u4e95\u6751\u897f\u53e3', u'2049': u'\u571f\u4e95\u6751\u897f\u53e3 \u81f3 \u957f\u5efa\u9a7e\u6821'}
oNqycwWK96VhQHx5eM0rBzaUrfZ4 gh_ebb0ceaa639e
[pid: 24268|app: 0|req: 1/1] 140.207.54.77 () {42 vars in 931 bytes} [Thu Jun 16 17:56:03 2016] POST /functiontest?signature=14fd79b7ee5b9d6e8f6804988da2df34396ad75c&timestamp=1466070963&nonce=864591483&openid=oNqycwWK96VhQHx5eM0rBzaUrfZ4&encrypt_type=aes&msg_signature=3a2d19ee072ce5a06a6276062147bc9cce10b6db => generated 415 bytes in 544 msecs (HTTP/1.1 200) 1 headers in 59 bytes (2 switches on core 0)
['1'] 1
['[', 'u', "'", '1', '7', '5', '3', "'"]
device_id=f8:a4:5f:11:21:79index=1is_change=0route_id=1timestamp=2016-03-31 15:39:02type=0client_credentialsf8:a4:5f:11:21:79
oNqycwWK96VhQHx5eM0rBzaUrfZ4 gh_ebb0ceaa639e
[pid: 24268|app: 0|req: 2/2] 140.207.54.77 () {42 vars in 931 bytes} [Thu Jun 16 17:56:12 2016] POST /functiontest?signature=7e0e2217d4bd3a37c697facad80613e3428bccec&timestamp=1466070972&nonce=146997176&openid=oNqycwWK96VhQHx5eM0rBzaUrfZ4&encrypt_type=aes&msg_signature=5b7ec71043665b82b3701ab9c29f8d200c75dae4 => generated 799 bytes in 152 msecs (HTTP/1.1 200) 1 headers in 59 bytes (2 switches on core 0)
Thu Jun 16 17:57:58 2016 - *** /home/dlgao/project/uwsgi.ini has been touched... grace them all !!! ***
...gracefully killing workers...
Gracefully killing worker 2 (pid: 24268)...
Gracefully killing worker 1 (pid: 24267)...
worker 1 buried after 1 seconds
worker 2 buried after 1 seconds
binary reloading uWSGI...
chdir() to /home/dlgao/project
closing all non-uwsgi socket fds > 2 (max_fd = 131072)...
found fd 3 mapped to socket 0 (10.160.156.96:9102)
running /usr/bin/uwsgi
[uWSGI] getting INI configuration from uwsgi.ini
open("./python_plugin.so"): No such file or directory [core/utils.c line 3675]
!!! UNABLE to load uWSGI plugin: ./python_plugin.so: cannot open shared object file: No such file or directory !!!
*** Starting uWSGI 2.0.11.1 (64bit) on [Thu Jun 16 17:57:59 2016] ***
compiled with version: 4.8.3 20140911 (Red Hat 4.8.3-9) on 20 August 2015 15:10:12
os: Linux-3.10.0-327.4.4.el7.x86_64 #1 SMP Thu Dec 17 15:51:24 EST 2015
nodename: hz-10-160-156-96.internal.lede.com
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 4
current working directory: /home/dlgao/project
detected binary path: /usr/bin/uwsgi
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /home/dlgao/project
your processes number limit is 31147
your memory page size is 4096 bytes
detected max file descriptor number: 131072
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 inherited INET address 10.160.156.96:9102 fd 3
Python version: 2.7.5 (default, Oct 11 2015, 17:47:16)  [GCC 4.8.3 20140911 (Red Hat 4.8.3-9)]
Python main interpreter initialized at 0xa30030
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 218304 bytes (213 KB) for 2 cores
*** Operational MODE: preforking ***
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0xa30030 pid: 22317 (default app)
*** uWSGI is running in multiple interpreter mode ***
gracefully (RE)spawned uWSGI master process (pid: 22317)
spawned uWSGI worker 1 (pid: 24286, cores: 1)
spawned uWSGI worker 2 (pid: 24287, cores: 1)
['909'] 909
device_id=f8:a4:5f:11:21:79is_exact=0keywords=909timestamp=2016-03-31 15:39:00client_credentialsf8:a4:5f:11:21:79
OrderedDict([('device_id', 'f8:a4:5f:11:21:79'), ('is_exact', 0), ('keywords', '909'), ('timestamp', '2016-03-31 15:39:00')]) 5ec2820150a9014c4334988bc534191f
device_id=f8:a4:5f:11:21:79index=1is_change=0route_id=1753timestamp=2016-03-31 15:39:02type=0client_credentialsf8:a4:5f:11:21:79
device_id=f8:a4:5f:11:21:79index=1is_change=1route_id=1753timestamp=2016-03-31 15:39:02type=0client_credentialsf8:a4:5f:11:21:79
$$$$$$$$$$$$$$$$$bus$$$$$$$$$$$$$$$$ {u'1753': u'\u957f\u5efa\u9a7e\u6821 \u81f3 \u571f\u4e95\u6751\u897f\u53e3', u'2049': u'\u571f\u4e95\u6751\u897f\u53e3 \u81f3 \u957f\u5efa\u9a7e\u6821'}
oNqycwWK96VhQHx5eM0rBzaUrfZ4 gh_ebb0ceaa639e
[pid: 24286|app: 0|req: 1/1] 140.207.54.77 () {42 vars in 931 bytes} [Thu Jun 16 17:58:13 2016] POST /functiontest?signature=f6e0237f157de48fdd988297ae15f79002351919&timestamp=1466071092&nonce=109888712&openid=oNqycwWK96VhQHx5eM0rBzaUrfZ4&encrypt_type=aes&msg_signature=36c8bdda6af8c3746ed9900bd7e4acede578cca2 => generated 415 bytes in 528 msecs (HTTP/1.1 200) 1 headers in 59 bytes (2 switches on core 0)
['2'] 2
['1753', '2049']
[pid: 24287|app: 0|req: 1/2] 140.207.54.77 () {42 vars in 933 bytes} [Thu Jun 16 17:58:16 2016] POST /functiontest?signature=7ac60b89c8ec64d157b9e557d1e085bf5d4826c8&timestamp=1466071096&nonce=1403295802&openid=oNqycwWK96VhQHx5eM0rBzaUrfZ4&encrypt_type=aes&msg_signature=8204c64dffc66c58b3921229d46d9972022887dd => generated 305 bytes in 63 msecs (HTTP/1.1 200) 1 headers in 59 bytes (2 switches on core 0)
['17'] 17
['1753', '2049']
[pid: 24286|app: 0|req: 2/3] 140.207.54.77 () {42 vars in 931 bytes} [Thu Jun 16 17:58:25 2016] POST /functiontest?signature=1fbd867582ce022e455b682d796f11e23c554215&timestamp=1466071105&nonce=312268662&openid=oNqycwWK96VhQHx5eM0rBzaUrfZ4&encrypt_type=aes&msg_signature=f0ef771ef0962d6435eb973d48f1adf71e2246fe => generated 305 bytes in 10 msecs (HTTP/1.1 200) 1 headers in 59 bytes (2 switches on core 0)
['1753'] 1753
['1753', '2049']
device_id=f8:a4:5f:11:21:79index=1is_change=0route_id=1753timestamp=2016-03-31 15:39:02type=0client_credentialsf8:a4:5f:11:21:79
oNqycwWK96VhQHx5eM0rBzaUrfZ4 gh_ebb0ceaa639e
[pid: 24286|app: 0|req: 3/4] 140.207.54.77 () {42 vars in 931 bytes} [Thu Jun 16 17:58:29 2016] POST /functiontest?signature=a26b22d7da2deadae1d43f7c8b565d967cad41e0&timestamp=1466071109&nonce=837655290&openid=oNqycwWK96VhQHx5eM0rBzaUrfZ4&encrypt_type=aes&msg_signature=98673a6f72f2d843fa32c7ff040117c7fd9317d4 => generated 1152 bytes in 185 msecs (HTTP/1.1 200) 1 headers in 59 bytes (2 switches on core 0)
['88'] 88
bus_num=9999device_id=f8:a4:5f:11:21:79index=88route_id=1753show_all=1timestamp=2016-03-31 15:39:08client_credentialsf8:a4:5f:11:21:79
oNqycwWK96VhQHx5eM0rBzaUrfZ4 gh_ebb0ceaa639e
[pid: 24286|app: 0|req: 4/5] 140.207.54.77 () {42 vars in 933 bytes} [Thu Jun 16 17:58:46 2016] POST /functiontest?signature=a17cb9b57e0cf77f0f673dc66a39ce4f78e461d9&timestamp=1466071126&nonce=1269879944&openid=oNqycwWK96VhQHx5eM0rBzaUrfZ4&encrypt_type=aes&msg_signature=31bfc5c868bce23ef28a8841703846154eb0ca71 => generated 1059 bytes in 4340 msecs (HTTP/1.1 200) 1 headers in 59 bytes (2 switches on core 0)
['2'] 2
device_id=f8:a4:5f:11:21:79is_exact=0keywords=2timestamp=2016-03-31 15:39:00client_credentialsf8:a4:5f:11:21:79
OrderedDict([('device_id', 'f8:a4:5f:11:21:79'), ('is_exact', 0), ('keywords', '2'), ('timestamp', '2016-03-31 15:39:00')]) 0dad48f090f2822e1f737c3517ec9a71
device_id=f8:a4:5f:11:21:79index=1is_change=0route_id=842timestamp=2016-03-31 15:39:02type=0client_credentialsf8:a4:5f:11:21:79
device_id=f8:a4:5f:11:21:79index=1is_change=1route_id=842timestamp=2016-03-31 15:39:02type=0client_credentialsf8:a4:5f:11:21:79
$$$$$$$$$$$$$$$$$bus$$$$$$$$$$$$$$$$ {u'843': u'\u5bbd\u8857\u8def\u53e3\u5357 \u81f3 \u6d77\u6237\u5c6f', u'842': u'\u6d77\u6237\u5c6f \u81f3 \u5bbd\u8857\u8def\u53e3\u5357'}
oNqycwWK96VhQHx5eM0rBzaUrfZ4 gh_ebb0ceaa639e
[pid: 24286|app: 0|req: 5/6] 140.207.54.77 () {42 vars in 933 bytes} [Thu Jun 16 18:00:14 2016] POST /functiontest?signature=f616bcc66b63fc0b8cf862186ad5430edc8d2de2&timestamp=1466071214&nonce=1147157451&openid=oNqycwWK96VhQHx5eM0rBzaUrfZ4&encrypt_type=aes&msg_signature=20f7c284e9a02364c147ddcd90fffbbe43fe0b49 => generated 407 bytes in 442 msecs (HTTP/1.1 200) 1 headers in 59 bytes (2 switches on core 0)
['909'] 909
['843', '842']
[pid: 24286|app: 0|req: 6/7] 140.207.54.77 () {42 vars in 931 bytes} [Thu Jun 16 18:00:21 2016] POST /functiontest?signature=14d9801de3601bcf663a4af653ab33c2bd009116&timestamp=1466071221&nonce=864085373&openid=oNqycwWK96VhQHx5eM0rBzaUrfZ4&encrypt_type=aes&msg_signature=292f1d562d18b085c5413446867bb3f170bd2688 => generated 305 bytes in 9 msecs (HTTP/1.1 200) 1 headers in 59 bytes (2 switches on core 0)
Thu Jun 16 18:05:33 2016 - *** /home/dlgao/project/uwsgi.ini has been touched... grace them all !!! ***
...gracefully killing workers...
Gracefully killing worker 1 (pid: 24286)...
Gracefully killing worker 2 (pid: 24287)...
worker 1 buried after 1 seconds
worker 2 buried after 1 seconds
binary reloading uWSGI...
chdir() to /home/dlgao/project
closing all non-uwsgi socket fds > 2 (max_fd = 131072)...
found fd 3 mapped to socket 0 (10.160.156.96:9102)
running /usr/bin/uwsgi
[uWSGI] getting INI configuration from uwsgi.ini
open("./python_plugin.so"): No such file or directory [core/utils.c line 3675]
!!! UNABLE to load uWSGI plugin: ./python_plugin.so: cannot open shared object file: No such file or directory !!!
*** Starting uWSGI 2.0.11.1 (64bit) on [Thu Jun 16 18:05:34 2016] ***
compiled with version: 4.8.3 20140911 (Red Hat 4.8.3-9) on 20 August 2015 15:10:12
os: Linux-3.10.0-327.4.4.el7.x86_64 #1 SMP Thu Dec 17 15:51:24 EST 2015
nodename: hz-10-160-156-96.internal.lede.com
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 4
current working directory: /home/dlgao/project
detected binary path: /usr/bin/uwsgi
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /home/dlgao/project
your processes number limit is 31147
your memory page size is 4096 bytes
detected max file descriptor number: 131072
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 inherited INET address 10.160.156.96:9102 fd 3
Python version: 2.7.5 (default, Oct 11 2015, 17:47:16)  [GCC 4.8.3 20140911 (Red Hat 4.8.3-9)]
Python main interpreter initialized at 0xb99030
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 218304 bytes (213 KB) for 2 cores
*** Operational MODE: preforking ***
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0xb99030 pid: 22317 (default app)
*** uWSGI is running in multiple interpreter mode ***
gracefully (RE)spawned uWSGI master process (pid: 22317)
spawned uWSGI worker 1 (pid: 24435, cores: 1)
spawned uWSGI worker 2 (pid: 24436, cores: 1)
['909'] 909
device_id=f8:a4:5f:11:21:79is_exact=0keywords=909timestamp=2016-03-31 15:39:00client_credentialsf8:a4:5f:11:21:79
OrderedDict([('device_id', 'f8:a4:5f:11:21:79'), ('is_exact', 0), ('keywords', '909'), ('timestamp', '2016-03-31 15:39:00')]) 5ec2820150a9014c4334988bc534191f
device_id=f8:a4:5f:11:21:79index=1is_change=0route_id=1753timestamp=2016-03-31 15:39:02type=0client_credentialsf8:a4:5f:11:21:79
device_id=f8:a4:5f:11:21:79index=1is_change=1route_id=1753timestamp=2016-03-31 15:39:02type=0client_credentialsf8:a4:5f:11:21:79
$$$$$$$$$$$$$$$$$bus$$$$$$$$$$$$$$$$ {u'1753': u'\u957f\u5efa\u9a7e\u6821 \u81f3 \u571f\u4e95\u6751\u897f\u53e3', u'2049': u'\u571f\u4e95\u6751\u897f\u53e3 \u81f3 \u957f\u5efa\u9a7e\u6821'}
oNqycwWK96VhQHx5eM0rBzaUrfZ4 gh_ebb0ceaa639e
[pid: 24436|app: 0|req: 1/1] 140.207.54.77 () {42 vars in 933 bytes} [Thu Jun 16 18:05:41 2016] POST /functiontest?signature=785e2bb35d91c63073f65fa6bd2d8339bf49e74c&timestamp=1466071541&nonce=1118241436&openid=oNqycwWK96VhQHx5eM0rBzaUrfZ4&encrypt_type=aes&msg_signature=9084345050d235b5760a6cebfcf2003d9602a668 => generated 454 bytes in 573 msecs (HTTP/1.1 200) 1 headers in 59 bytes (2 switches on core 0)
[] clear
oNqycwWK96VhQHx5eM0rBzaUrfZ4 gh_ebb0ceaa639e
[pid: 24436|app: 0|req: 2/2] 140.207.54.77 () {42 vars in 931 bytes} [Thu Jun 16 18:05:47 2016] POST /functiontest?signature=ca3643df312a6b6fa998bf9cf1ca5926f47ee800&timestamp=1466071547&nonce=149720179&openid=oNqycwWK96VhQHx5eM0rBzaUrfZ4&encrypt_type=aes&msg_signature=6520154e736f193f7081c5137617feb7f3e59103 => generated 280 bytes in 7 msecs (HTTP/1.1 200) 1 headers in 59 bytes (2 switches on core 0)
Thu Jun 16 18:06:31 2016 - *** /home/dlgao/project/uwsgi.ini has been touched... grace them all !!! ***
...gracefully killing workers...
Gracefully killing worker 2 (pid: 24436)...
Gracefully killing worker 1 (pid: 24435)...
worker 1 buried after 1 seconds
worker 2 buried after 1 seconds
binary reloading uWSGI...
chdir() to /home/dlgao/project
closing all non-uwsgi socket fds > 2 (max_fd = 131072)...
found fd 3 mapped to socket 0 (10.160.156.96:9102)
running /usr/bin/uwsgi
[uWSGI] getting INI configuration from uwsgi.ini
open("./python_plugin.so"): No such file or directory [core/utils.c line 3675]
!!! UNABLE to load uWSGI plugin: ./python_plugin.so: cannot open shared object file: No such file or directory !!!
*** Starting uWSGI 2.0.11.1 (64bit) on [Thu Jun 16 18:06:32 2016] ***
compiled with version: 4.8.3 20140911 (Red Hat 4.8.3-9) on 20 August 2015 15:10:12
os: Linux-3.10.0-327.4.4.el7.x86_64 #1 SMP Thu Dec 17 15:51:24 EST 2015
nodename: hz-10-160-156-96.internal.lede.com
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 4
current working directory: /home/dlgao/project
detected binary path: /usr/bin/uwsgi
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /home/dlgao/project
your processes number limit is 31147
your memory page size is 4096 bytes
detected max file descriptor number: 131072
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 inherited INET address 10.160.156.96:9102 fd 3
Python version: 2.7.5 (default, Oct 11 2015, 17:47:16)  [GCC 4.8.3 20140911 (Red Hat 4.8.3-9)]
Python main interpreter initialized at 0x209f030
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 218304 bytes (213 KB) for 2 cores
*** Operational MODE: preforking ***
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x209f030 pid: 22317 (default app)
*** uWSGI is running in multiple interpreter mode ***
gracefully (RE)spawned uWSGI master process (pid: 22317)
spawned uWSGI worker 1 (pid: 24450, cores: 1)
spawned uWSGI worker 2 (pid: 24451, cores: 1)
[] CleAr
oNqycwWK96VhQHx5eM0rBzaUrfZ4 gh_ebb0ceaa639e
[pid: 24451|app: 0|req: 1/1] 140.207.54.77 () {42 vars in 931 bytes} [Thu Jun 16 18:06:39 2016] POST /functiontest?signature=5300f29bdbd28c5b6508f3e678e7599f039ccd49&timestamp=1466071599&nonce=781676848&openid=oNqycwWK96VhQHx5eM0rBzaUrfZ4&encrypt_type=aes&msg_signature=cb725b7b983a0e764315f2696955810124c2fdf1 => generated 240 bytes in 68 msecs (HTTP/1.1 200) 1 headers in 59 bytes (2 switches on core 0)
[] CleAr
oNqycwWK96VhQHx5eM0rBzaUrfZ4 gh_ebb0ceaa639e
[pid: 24451|app: 0|req: 2/2] 140.207.54.77 () {42 vars in 931 bytes} [Thu Jun 16 18:06:49 2016] POST /functiontest?signature=731906e1d86bc1af1293625e242e140a76cd7d3d&timestamp=1466071609&nonce=121461347&openid=oNqycwWK96VhQHx5eM0rBzaUrfZ4&encrypt_type=aes&msg_signature=edd7005e0cdde1597665c299abcf9db623b42cd9 => generated 240 bytes in 7 msecs (HTTP/1.1 200) 1 headers in 59 bytes (2 switches on core 0)
[] CleAr
oNqycwWK96VhQHx5eM0rBzaUrfZ4 gh_ebb0ceaa639e
[pid: 24451|app: 0|req: 3/3] 140.207.54.77 () {42 vars in 933 bytes} [Thu Jun 16 18:06:59 2016] POST /functiontest?signature=74b73e823ab54fe327f4fb41c46e414cccfd1af6&timestamp=1466071619&nonce=1450287654&openid=oNqycwWK96VhQHx5eM0rBzaUrfZ4&encrypt_type=aes&msg_signature=30c39ddfe3a306e542c7e2470d2493925b550593 => generated 240 bytes in 8 msecs (HTTP/1.1 200) 1 headers in 59 bytes (2 switches on core 0)
Thu Jun 16 18:07:25 2016 - *** /home/dlgao/project/uwsgi.ini has been touched... grace them all !!! ***
...gracefully killing workers...
Gracefully killing worker 2 (pid: 24451)...
Gracefully killing worker 1 (pid: 24450)...
worker 1 buried after 1 seconds
worker 2 buried after 1 seconds
binary reloading uWSGI...
chdir() to /home/dlgao/project
closing all non-uwsgi socket fds > 2 (max_fd = 131072)...
found fd 3 mapped to socket 0 (10.160.156.96:9102)
running /usr/bin/uwsgi
[uWSGI] getting INI configuration from uwsgi.ini
open("./python_plugin.so"): No such file or directory [core/utils.c line 3675]
!!! UNABLE to load uWSGI plugin: ./python_plugin.so: cannot open shared object file: No such file or directory !!!
*** Starting uWSGI 2.0.11.1 (64bit) on [Thu Jun 16 18:07:26 2016] ***
compiled with version: 4.8.3 20140911 (Red Hat 4.8.3-9) on 20 August 2015 15:10:12
os: Linux-3.10.0-327.4.4.el7.x86_64 #1 SMP Thu Dec 17 15:51:24 EST 2015
nodename: hz-10-160-156-96.internal.lede.com
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 4
current working directory: /home/dlgao/project
detected binary path: /usr/bin/uwsgi
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /home/dlgao/project
your processes number limit is 31147
your memory page size is 4096 bytes
detected max file descriptor number: 131072
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 inherited INET address 10.160.156.96:9102 fd 3
Python version: 2.7.5 (default, Oct 11 2015, 17:47:16)  [GCC 4.8.3 20140911 (Red Hat 4.8.3-9)]
Python main interpreter initialized at 0x268e030
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 218304 bytes (213 KB) for 2 cores
*** Operational MODE: preforking ***
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x268e030 pid: 22317 (default app)
*** uWSGI is running in multiple interpreter mode ***
gracefully (RE)spawned uWSGI master process (pid: 22317)
spawned uWSGI worker 1 (pid: 24463, cores: 1)
spawned uWSGI worker 2 (pid: 24464, cores: 1)
[] clear
oNqycwWK96VhQHx5eM0rBzaUrfZ4 gh_ebb0ceaa639e
[pid: 24464|app: 0|req: 1/1] 140.207.54.77 () {42 vars in 931 bytes} [Thu Jun 16 18:07:30 2016] POST /functiontest?signature=9c66df5aa026c39366c267b32405263e75f94df5&timestamp=1466071650&nonce=374742902&openid=oNqycwWK96VhQHx5eM0rBzaUrfZ4&encrypt_type=aes&msg_signature=7a0ba9c2c0be7a72a27648f2a045fe09e57ffa5b => generated 275 bytes in 70 msecs (HTTP/1.1 200) 1 headers in 59 bytes (2 switches on core 0)
['909'] 909
device_id=f8:a4:5f:11:21:79is_exact=0keywords=909timestamp=2016-03-31 15:39:00client_credentialsf8:a4:5f:11:21:79
OrderedDict([('device_id', 'f8:a4:5f:11:21:79'), ('is_exact', 0), ('keywords', '909'), ('timestamp', '2016-03-31 15:39:00')]) 5ec2820150a9014c4334988bc534191f
device_id=f8:a4:5f:11:21:79index=1is_change=0route_id=1753timestamp=2016-03-31 15:39:02type=0client_credentialsf8:a4:5f:11:21:79
device_id=f8:a4:5f:11:21:79index=1is_change=1route_id=1753timestamp=2016-03-31 15:39:02type=0client_credentialsf8:a4:5f:11:21:79
$$$$$$$$$$$$$$$$$bus$$$$$$$$$$$$$$$$ {u'1753': u'\u957f\u5efa\u9a7e\u6821 \u81f3 \u571f\u4e95\u6751\u897f\u53e3', u'2049': u'\u571f\u4e95\u6751\u897f\u53e3 \u81f3 \u957f\u5efa\u9a7e\u6821'}
oNqycwWK96VhQHx5eM0rBzaUrfZ4 gh_ebb0ceaa639e
[pid: 24463|app: 0|req: 1/2] 140.207.54.77 () {42 vars in 931 bytes} [Thu Jun 16 18:07:35 2016] POST /functiontest?signature=847dbf7e02e4347906db18ac0f1493b48db4de6d&timestamp=1466071655&nonce=407861962&openid=oNqycwWK96VhQHx5eM0rBzaUrfZ4&encrypt_type=aes&msg_signature=6f8f6d2bdaf418b9fbe00bcf81fe779b7bf47739 => generated 454 bytes in 521 msecs (HTTP/1.1 200) 1 headers in 59 bytes (2 switches on core 0)
['21'] 21
['1753', '2049']
[pid: 24464|app: 0|req: 2/3] 140.207.54.77 () {42 vars in 931 bytes} [Thu Jun 16 18:07:38 2016] POST /functiontest?signature=c4ca0ebc83bbf1818b5bd320a3d1ee0d4e3f933e&timestamp=1466071658&nonce=498707556&openid=oNqycwWK96VhQHx5eM0rBzaUrfZ4&encrypt_type=aes&msg_signature=d30423fb5063009b2340f94ab17143c02246850b => generated 344 bytes in 8 msecs (HTTP/1.1 200) 1 headers in 59 bytes (2 switches on core 0)
['12'] 12
['1753', '2049']
[pid: 24464|app: 0|req: 3/4] 140.207.54.77 () {42 vars in 931 bytes} [Thu Jun 16 18:07:42 2016] POST /functiontest?signature=6ff49034ee2cc3c74f70857497c2c6be7f1e3742&timestamp=1466071662&nonce=607183453&openid=oNqycwWK96VhQHx5eM0rBzaUrfZ4&encrypt_type=aes&msg_signature=28725d1fa1617043a70a809696ba063834bbd3d0 => generated 344 bytes in 8 msecs (HTTP/1.1 200) 1 headers in 59 bytes (2 switches on core 0)
[] clear
oNqycwWK96VhQHx5eM0rBzaUrfZ4 gh_ebb0ceaa639e
[pid: 24463|app: 0|req: 2/5] 140.207.54.77 () {42 vars in 931 bytes} [Thu Jun 16 18:07:44 2016] POST /functiontest?signature=bf0dac1c3373dd627fd0a629a82d370bf051b833&timestamp=1466071664&nonce=690533635&openid=oNqycwWK96VhQHx5eM0rBzaUrfZ4&encrypt_type=aes&msg_signature=893c5776d3566ddd88123f3782c4c9a6d7e7827a => generated 275 bytes in 9 msecs (HTTP/1.1 200) 1 headers in 59 bytes (2 switches on core 0)
['2'] 2
device_id=f8:a4:5f:11:21:79is_exact=0keywords=2timestamp=2016-03-31 15:39:00client_credentialsf8:a4:5f:11:21:79
OrderedDict([('device_id', 'f8:a4:5f:11:21:79'), ('is_exact', 0), ('keywords', '2'), ('timestamp', '2016-03-31 15:39:00')]) 0dad48f090f2822e1f737c3517ec9a71
device_id=f8:a4:5f:11:21:79index=1is_change=0route_id=842timestamp=2016-03-31 15:39:02type=0client_credentialsf8:a4:5f:11:21:79
device_id=f8:a4:5f:11:21:79index=1is_change=1route_id=842timestamp=2016-03-31 15:39:02type=0client_credentialsf8:a4:5f:11:21:79
$$$$$$$$$$$$$$$$$bus$$$$$$$$$$$$$$$$ {u'843': u'\u5bbd\u8857\u8def\u53e3\u5357 \u81f3 \u6d77\u6237\u5c6f', u'842': u'\u6d77\u6237\u5c6f \u81f3 \u5bbd\u8857\u8def\u53e3\u5357'}
oNqycwWK96VhQHx5eM0rBzaUrfZ4 gh_ebb0ceaa639e
[pid: 24464|app: 0|req: 4/6] 140.207.54.77 () {42 vars in 933 bytes} [Thu Jun 16 18:07:45 2016] POST /functiontest?signature=b51ca34acf486103f7b5f551e79814790be41f54&timestamp=1466071665&nonce=1250677609&openid=oNqycwWK96VhQHx5eM0rBzaUrfZ4&encrypt_type=aes&msg_signature=03981164c51c1948e8057a04c39b7f956cbf2268 => generated 446 bytes in 868 msecs (HTTP/1.1 200) 1 headers in 59 bytes (2 switches on core 0)
['843'] 843
['843', '842']
device_id=f8:a4:5f:11:21:79index=1is_change=0route_id=843timestamp=2016-03-31 15:39:02type=0client_credentialsf8:a4:5f:11:21:79
oNqycwWK96VhQHx5eM0rBzaUrfZ4 gh_ebb0ceaa639e
[pid: 24463|app: 0|req: 3/7] 140.207.54.77 () {42 vars in 933 bytes} [Thu Jun 16 18:07:49 2016] POST /functiontest?signature=ebc6cf255a4fb43885c85de7ed3b5603503d57e8&timestamp=1466071669&nonce=1705880025&openid=oNqycwWK96VhQHx5eM0rBzaUrfZ4&encrypt_type=aes&msg_signature=cdb741adeaef998141843face7754e40a62cfba4 => generated 547 bytes in 157 msecs (HTTP/1.1 200) 1 headers in 59 bytes (2 switches on core 0)
['45'] 45
[pid: 24464|app: 0|req: 5/8] 140.207.54.77 () {42 vars in 933 bytes} [Thu Jun 16 18:07:55 2016] POST /functiontest?signature=2611553ec1fac6a4140f13152e982944e53a9de1&timestamp=1466071675&nonce=1430542628&openid=oNqycwWK96VhQHx5eM0rBzaUrfZ4&encrypt_type=aes&msg_signature=901e58865cf679894ab7c60c37f849a5b0973a2a => generated 344 bytes in 8 msecs (HTTP/1.1 200) 1 headers in 59 bytes (2 switches on core 0)
['11'] 11
bus_num=9999device_id=f8:a4:5f:11:21:79index=11route_id=843show_all=1timestamp=2016-03-31 15:39:08client_credentialsf8:a4:5f:11:21:79
oNqycwWK96VhQHx5eM0rBzaUrfZ4 gh_ebb0ceaa639e
[pid: 24463|app: 0|req: 4/9] 140.207.54.77 () {42 vars in 933 bytes} [Thu Jun 16 18:07:58 2016] POST /functiontest?signature=af4065c2857433bfd3117e39963b2c72afda6fbd&timestamp=1466071678&nonce=2088379946&openid=oNqycwWK96VhQHx5eM0rBzaUrfZ4&encrypt_type=aes&msg_signature=c685b94cfb311cec126d5e8f52361d1c80ae77f3 => generated 600 bytes in 4361 msecs (HTTP/1.1 200) 1 headers in 59 bytes (2 switches on core 0)
['379'] 379
device_id=f8:a4:5f:11:21:79is_exact=0keywords=379timestamp=2016-03-31 15:39:00client_credentialsf8:a4:5f:11:21:79
OrderedDict([('device_id', 'f8:a4:5f:11:21:79'), ('is_exact', 0), ('keywords', '379'), ('timestamp', '2016-03-31 15:39:00')]) 720e3a7cd5069ec750aa630fe0cb5539
device_id=f8:a4:5f:11:21:79index=1is_change=0route_id=593timestamp=2016-03-31 15:39:02type=0client_credentialsf8:a4:5f:11:21:79
device_id=f8:a4:5f:11:21:79index=1is_change=1route_id=593timestamp=2016-03-31 15:39:02type=0client_credentialsf8:a4:5f:11:21:79
$$$$$$$$$$$$$$$$$bus$$$$$$$$$$$$$$$$ {u'593': u'\u80b2\u65b0\u5c0f\u533a \u81f3 \u5de6\u5bb6\u5e84', u'594': u'\u5de6\u5bb6\u5e84 \u81f3 \u80b2\u65b0\u5c0f\u533a'}
oNqycwWK96VhQHx5eM0rBzaUrfZ4 gh_ebb0ceaa639e
[pid: 24464|app: 0|req: 6/10] 140.207.54.77 () {42 vars in 931 bytes} [Thu Jun 16 18:09:16 2016] POST /functiontest?signature=2b42ed5f560eb4da3267c65be7d9c37e0340249e&timestamp=1466071756&nonce=625097658&openid=oNqycwWK96VhQHx5eM0rBzaUrfZ4&encrypt_type=aes&msg_signature=bd048b3d0c51cda0fb044819d84efb307530e393 => generated 440 bytes in 733 msecs (HTTP/1.1 200) 1 headers in 59 bytes (2 switches on core 0)
['594'] 594
['593', '594']
device_id=f8:a4:5f:11:21:79index=1is_change=0route_id=594timestamp=2016-03-31 15:39:02type=0client_credentialsf8:a4:5f:11:21:79
oNqycwWK96VhQHx5eM0rBzaUrfZ4 gh_ebb0ceaa639e
[pid: 24464|app: 0|req: 7/11] 140.207.54.77 () {42 vars in 931 bytes} [Thu Jun 16 18:09:21 2016] POST /functiontest?signature=8f91817acd261e46b3e25fdd9133d1a2915e35ec&timestamp=1466071761&nonce=142939810&openid=oNqycwWK96VhQHx5eM0rBzaUrfZ4&encrypt_type=aes&msg_signature=756ad603e5955ae5f31905dafab9ecb232635781 => generated 797 bytes in 180 msecs (HTTP/1.1 200) 1 headers in 59 bytes (2 switches on core 0)
['12'] 12
bus_num=9999device_id=f8:a4:5f:11:21:79index=12route_id=594show_all=1timestamp=2016-03-31 15:39:08client_credentialsf8:a4:5f:11:21:79
oNqycwWK96VhQHx5eM0rBzaUrfZ4 gh_ebb0ceaa639e
[pid: 24464|app: 0|req: 8/12] 140.207.54.77 () {42 vars in 931 bytes} [Thu Jun 16 18:09:25 2016] POST /functiontest?signature=dd1bde8faca6c2fcf6a65da59aad97c9102ac573&timestamp=1466071765&nonce=480691648&openid=oNqycwWK96VhQHx5eM0rBzaUrfZ4&encrypt_type=aes&msg_signature=e1e722f3794bba48f17c7e361e1d492ef537d998 => generated 466 bytes in 4345 msecs (HTTP/1.1 200) 1 headers in 59 bytes (2 switches on core 0)
